### ISSUE TITLE
Track exception and native crash is missing.

### ISSUE THREAD

**Issue by Caij** [microsoft/appcenter-sdk-android#1139]
Track exception and native crash is missing.  
And can support multiple processes?

**Comment by AnastasiaKubova** [comment]
Hi, @Caij! Could you please be more specific and provide more details about your issue?

**Comment by Caij** [comment]
1. sdk unsupport android native crash report。
2. sdk unsupport custom exception report.
3. sdk unsupport android multiple processes.

**Comment by MatkovIvan** [comment]
Hi @Caij,

Thanks for getting in touch!
1. It's supported, please have a look at our [Android NDK](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk) documentation.
2. Duplicate of #933
3. Could you please submit a dedicated feature request in [our public App Center repo](https://github.com/Microsoft/appcenter/issues) or give an existing feature a :+1: This will help our team prioritize the features accordingly.

Best,
Ivan

**Comment by annakocheshkova** [comment]
Hi there @Caij do you have any more suggestions?

**Comment by Caij** [comment]
Is there an API for automatically uploading a mapping file?

**Comment by Jamminroot** [comment]
@Caij you can refer to [swagger](https://openapi.appcenter.ms/) for list of avaliable API's

**Comment by winnieli1208** [comment]
Hi @Caij you can use our [upload symbols API](https://openapi.appcenter.ms/#/crash/symbolUploads_create) to upload your Android mappings. Instructions are [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/iOS-symbolication#app-center-api).

**Comment by Caij** [comment]
I am migrating from the fabric.
There are several disadvantages to comparison:
1. Sdk unsupport custom exception report
2. There is no plugin that automatically uploads mapping
3. Analytics Overview has no new users and retention rates.
4. Native crash ndk access is more troublesome.

Thans！
