### ISSUE TITLE
Update SDK & Support Libs for Push

### ISSUE THREAD

**Issue by kjf3006** [microsoft/appcenter-sdk-android#1159]
Please update push-module to current SKD version (28), especially com.android.support packages.

**Comment by annakocheshkova** [comment]
Hi @kjf3006! We use 28 version, if this is what you're about: https://github.com/microsoft/appcenter-sdk-android/blob/ddabc61899fe34355aa0f8422723d540fbea1d05/versions.gradle#L14

**Comment by kjf3006** [comment]
When I include `com.microsoft.appcenter:appcenter-push:2.0.0` with `com.android.support:appcompat-v7:28.0.0` at the same time, I get the following message:

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 26.1.0. Examples include com.android.support:animated-vector-drawable:28.0.0 and com.android.support:support-media-compat:26.1.0 less...

This error get's resolved with this include statement:

`implementation ("com.microsoft.appcenter:appcenter-push:$appCenterSdkVersion") {
        exclude group: 'com.android.support'
    }`

**Comment by annakocheshkova** [comment]
@kjf3006 probably firebase sdk which is referenced by our push lib uses lower support lib versions. I will confirm with the team if we have plans to upgrade firebase versions.
For now, your solution is the only way to resolve the conflict, yeah.

**Comment by guperrot** [comment]
@kjf3006 Can you run `./gradlew :app:dependencies` and share the output with us? The command path might be different for you if you have a complex setup (go to the folder containing the build.gradle for the app project, not root, then add as many `../` as necessary to invoke `gradlew dependencies`).

**Comment by guperrot** [comment]
Even the latest firebase library (18.0.0) still depends on `com.android.support:support-v4:26.1.0` so AppCenter is not causing the conflict directly (AppCenter does not have support dependencies directly but only Firebase which itself depends on older support lib).

Usually an application has to resolve conflicts like this instead of using exclude:

```groovy
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
```

Have you tried that?

**Comment by kjf3006** [comment]
Yes, adding `implementation 'com.android.support:support-v4:28.0.0'` solves the error message. Thanks, I've never heard of this before!

**Comment by guperrot** [comment]
You're welcome.
We cannot really add this one dependency to appcenter explicitly to v28 as it could cause problems for other customers not yet using support v28.
We updated to the latest Firebase in dev branch and it's still referencing v26.1.
Looks like the best solution for now is to add this line to solve the linter error.
