### ISSUE TITLE
Crash java.lang.SecurityException on app start cause by BrowserUtils.openBrowser

### ISSUE THREAD

**Issue by luboganev** [microsoft/appcenter-sdk-android#1162]
### **Description**

Integrated AppCenter crash reporting, analytics and distribute. On starting the main activity of my application, it crashes the following crash log:

```
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://install.appcenter.ms/... cmp=com.opera.browser/.leanplum.LeanplumCatchActivity } from ProcessRecord{a4a5f86 23827:**my_package_name***/u0a198} (pid=23827, uid=10198) not exported from uid 10145
        ........
        at com.microsoft.appcenter.distribute.BrowserUtils.openBrowser(BrowserUtils.java:93)
        at com.microsoft.appcenter.distribute.DistributeUtils.updateSetupUsingBrowser(DistributeUtils.java:175)
        at com.microsoft.appcenter.distribute.Distribute.resumeDistributeWorkflow(Distribute.java:827)
        at com.microsoft.appcenter.distribute.Distribute.onActivityResumed(Distribute.java:481)
        at android.app.Application.dispatchActivityResumed(Application.java:218)
        ...........
```

My suspicion is that either the Opera does not support this type of launch, or simply the Xiaomi Redmi 5A Android does not allow directly starting activity by package name and class name. I suppose it requires that the user always goes through the IntentChooser.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use Xiaomi Redmi 5A
2. Set Opera as the default browser.

### **Details**

1. Which SDK version are you using?
    - 2.0.0
2. Which OS version did you experience the issue on?
    - Android 8.1.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Xiaomi Redmi 5A , physical device
4. What third party libraries are you using?
    - org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21
    - androidx.appcompat:appcompat:1.0.2
    - com.google.android.material:material:1.0.0
    - androidx.core:core-ktx:1.0.2
    - androidx.constraintlayout:constraintlayout:1.1.3
    - com.jakewharton.timber:timber:4.7.1
    - io.reactivex.rxjava2:rxjava:2.2.0
    - io.reactivex.rxjava2:rxkotlin:2.2.0
    - io.reactivex.rxjava2:rxandroid:2.1.0
    - com.microsoft.appcenter:appcenter-analytics:2.0.0
    - com.microsoft.appcenter:appcenter-crashes:2.0.0
    - com.microsoft.appcenter:appcenter-distribute:2.0.0
    - com.google.protobuf:protobuf-lite:3.0.0
    - androidx.lifecycle:lifecycle-viewmodel-ktx:2.0.0
    - androidx.navigation:navigation-fragment-ktx:2.0.0
    - androidx.navigation:navigation-ui-ktx:2.0.0
    - androidx.work:work-runtime-ktx:2.0.1
    - androidx.multidex:multidex:2.0.1
    - com.google.android.gms:play-services-location:16.0.0
    - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1
    - org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1
    - androidx.recyclerview:recyclerview:1.0.0
    - com.google.firebase:firebase-core:16.0.9
    - com.google.firebase:firebase-auth:17.0.0
    - com.google.firebase:firebase-storage:17.0.0
    - com.google.android.gms:play-services-maps:16.1.0

5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

Just a side note before you review the logs:
- Normally it is not possible to provide logs for the Distribute, due to the fact that it only works if the app is not in debuggable state. The cause is in this line in the SDK's Distribute.java:

``` 
/* Don't go any further it this is a debug app. */
            if ((mContext.getApplicationInfo().flags & FLAG_DEBUGGABLE) == FLAG_DEBUGGABLE) {
                AppCenterLog.info(LOG_TAG, "Not checking in app updates in debug.");
                mWorkflowCompleted = true;
                return;
            }
```

In order to provide you the log below, I need to set a breakpoint at runtime and overwrite the debuggable flag `mContext.getApplicationInfo().flags` to allow for the logic to continue. Testing this would be much more convenient if you merge one of the open feature requests for making this debuggable behavior optional. Anyway, allowing artificially the logic to continue, this is what happens.

```
I/AppCenter: App Center SDK configured successfully.
D/AppCenter: Cannot read instrumentation variables in a non-test environment.
D/AppCenter: Cannot read instrumentation variables in a non-test environment.
D/AppCenter: Cannot read instrumentation variables in a non-test environment.
D/AppCenter: Using appcenter.0.AES/CBC/PKCS7Padding/256
D/AppCenter: Using appcenter.0.RSA/ECB/PKCS1Padding/2048
I/AppCenterDistribute: Launcher activity restarted.
D/AppCenter: Loaded stored sessions: {1558107558722=1558107558722/6b51a420-8ca6-4659-8d99-eb9f9c72c76e/1558107558387, 1558107600673=1558107600673//1558107600672, 1558107785616=1558107785616//1558107785615, 1558107786348=1558107786348/ee424fa1-6438-416c-be34-afd7afa96986/1558107785615, 1558107795276=1558107795276//1558107795275, 1558107795835=1558107795835/9cadad71-4cdc-4bf8-9857-791b701fab31/1558107795275, 1558109636803=1558109636803//1558109636790, 1558109639041=1558109639041/e2e6e7d8-65f8-4bad-a21a-4a9baeb7f536/1558109636790, 1558109713851=1558109713851//1558109713833, 1558109715294=1558109715294/411e3f0a-5cfe-4f01-9b53-b7c50de28f6c/1558109713833}
D/AppCenter: Network 118 is available.
D/AppCenter: Network has been connected.
I/AppCenter: Changed maximum database size to 10485760 bytes.
D/AppCenter: addGroup(group_core)
D/AppCenter: checkPendingLogs(group_core) pendingLogCount=1
D/AppCenter: App Center initialized.
D/AppCenter: removeGroup(group_analytics)
D/AppCenter: removeGroup(group_analytics/one)
D/AppCenter: addGroup(group_analytics)
D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=2
D/AppCenter: addGroup(group_analytics/one)
D/AppCenter: checkPendingLogs(group_analytics/one) pendingLogCount=0
I/AppCenter: Analytics service started from application.
D/AppCenter: removeGroup(groupErrors)
D/AppCenter: removeGroup(groupErrors/one)
D/AppCenter: addGroup(groupErrors)
D/AppCenter: checkPendingLogs(groupErrors) pendingLogCount=0
D/AppCenter: addGroup(groupErrors/one)
D/AppCenter: checkPendingLogs(groupErrors/one) pendingLogCount=0
D/AppCenterCrashes: Processing crash report for the last session.
D/AppCenterCrashes: Processed crash report for the last session.
D/AppCenterCrashes: Process pending error file: /data/user/0/*******my_package_name******/files/error/dcd6a449-c003-47fc-ab5d-526013db57e1.json
I/AppCenter: Crashes service started from application.
D/AppCenter: removeGroup(group_distribute)
D/AppCenter: removeGroup(group_distribute/one)
D/AppCenter: addGroup(group_distribute)
D/AppCenter: checkPendingLogs(group_distribute) pendingLogCount=0
D/AppCenter: addGroup(group_distribute/one)
D/AppCenter: checkPendingLogs(group_distribute/one) pendingLogCount=0
I/AppCenter: Distribute service started from application.
D/AppCenter: Storing a log to the Persistence database for log type startService with flags=1
D/AppCenter: Stored a log to the Persistence database for log type startService with databaseId=39
D/AppCenter: enqueue(group_core) pendingLogCount=2
D/AppCenter: checkPendingLogs(group_core) pendingLogCount=2
D/AppCenter: Storing a log to the Persistence database for log type event with flags=1
D/AppCenter: Stored a log to the Persistence database for log type event with databaseId=40
D/AppCenter: enqueue(group_analytics) pendingLogCount=3
D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=3
D/AppCenterAnalytics: onActivityResumed
D/AppCenter: Storing a log to the Persistence database for log type startSession with flags=1
D/AppCenter: Stored a log to the Persistence database for log type startSession with databaseId=41
D/AppCenter: enqueue(group_analytics) pendingLogCount=4
D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=4
D/AppCenter: triggerIngestion(group_core) pendingLogCount=2
D/AppCenter: Trying to get 2 logs from the Persistence database for group_core
D/AppCenter: Returning 2 log(s) with an ID, dfbb94dc-0df9-4445-aff8-9dc2d869042c
D/AppCenter: The SID/ID pairs for returning log(s) is/are:
D/AppCenter: 	null / 36
D/AppCenter: 	null / 39
D/AppCenter: ingestLogs(group_core,dfbb94dc-0df9-4445-aff8-9dc2d869042c) pendingLogCount=0
D/AppCenter: triggerIngestion(group_analytics) pendingLogCount=4
D/AppCenter: Trying to get 4 logs from the Persistence database for group_analytics
D/AppCenter: Returning 4 log(s) with an ID, bfe6744b-35d0-4b07-8e76-18b65f92b4cb
D/AppCenter: The SID/ID pairs for returning log(s) is/are:
D/AppCenter: 	null / 37
D/AppCenter: 	411e3f0a-5cfe-4f01-9b53-b7c50de28f6c / 38
D/AppCenter: 	null / 40
D/AppCenter: 	4e99dc03-487d-4968-87fd-1b10c4a50802 / 41
D/AppCenter: ingestLogs(group_analytics,bfe6744b-35d0-4b07-8e76-18b65f92b4cb) pendingLogCount=0
D/AppCenterDistribute: InstallerPackageName=null
D/AppCenterDistribute: No token, need to open browser to url=https://install.appcenter.ms/apps/f626dbb0-bd87-46e4-9214-14d06a2fdac5/update-setup/?release_hash=23d245d9f8701123ee196698c462ccbb5ff424cd533e746e85a7a329db79ccac&redirect_id=*******my_package_name******&redirect_scheme=appcenter&request_id=97fda018-869b-4f73-9a21-2884e41cca4e&platform=Android&enable_failure_redirect=true&install_id=44d98f13-9ddb-4367-82c5-0add4dc419fe
D/AppCenterDistribute: Default browser seems to be com.android.browser/com.android.browser.LauncherActivity
D/AppCenterDistribute: Default browser is actually a picker...
D/AppCenterDistribute: Picking first browser in list.
D/AppCenterDistribute: Launch browser=com.opera.browser/com.opera.browser.leanplum.LeanplumCatchActivity
D/AppCenterCrashes: Saving uncaught exception.
D/AppCenterCrashes: Saved JSON content for ingestion into /data/user/0/*******my_package_name******/files/error/0e2db6b7-0059-4ec9-b895-11410dabc9f0.json
D/AppCenterCrashes: Saved Throwable as is for client side inspection in /data/user/0/*******my_package_name******/files/error/0e2db6b7-0059-4ec9-b895-11410dabc9f0.throwable throwable:
    java.lang.RuntimeException: Unable to resume activity {*******my_package_name******/*******my_package_name******.ui.MainActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://install.appcenter.ms/... cmp=com.opera.browser/.leanplum.LeanplumCatchActivity } from ProcessRecord{d7a878b 27938:*******my_package_name******/u0a198} (pid=27938, uid=10198) not exported from uid 10145
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3627)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2901)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://install.appcenter.ms/... cmp=com.opera.browser/.leanplum.LeanplumCatchActivity } from ProcessRecord{d7a878b 27938:*******my_package_name******/u0a198} (pid=27938, uid=10198) not exported from uid 10145
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4437)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
        at android.app.Activity.startActivityForResult(Activity.java:4555)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4513)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4874)
        at android.app.Activity.startActivity(Activity.java:4842)
        at com.microsoft.appcenter.distribute.BrowserUtils.openBrowser(BrowserUtils.java:93)
        at com.microsoft.appcenter.distribute.DistributeUtils.updateSetupUsingBrowser(DistributeUtils.java:175)
        at com.microsoft.appcenter.distribute.Distribute.resumeDistributeWorkflow(Distribute.java:827)
        at com.microsoft.appcenter.distribute.Distribute.onActivityResumed(Distribute.java:481)
        at android.app.Application.dispatchActivityResumed(Application.java:218)
        at android.app.Activity.onResume(Activity.java:1345)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:514)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
        at android.app.Activity.performResume(Activity.java:7196)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2901) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
2019-05-17 18:18:37.379 27938-27995/*******my_package_name****** D/AppCenter: Cleared pending log states
2019-05-17 18:18:37.379 27938-27995/*******my_package_name****** D/AppCenter: Channel completed shutdown.
```

**Comment by luboganev** [comment]
Hello @annakocheshkova ,

Thanks for the quick reply. The Opera version is this one:
https://play.google.com/store/apps/details?id=com.opera.browser

**Comment by guperrot** [comment]
Hi @luboganev, can you add this code to main activity onCreate just to test you can repro the crash every time?

```
/* Open a browser but we don't want a chooser U.I. to pop. */
        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://install.appcenter.ms/apps/f626dbb0-bd87-46e4-9214-14d06a2fdac5/update-setup/?release_hash=23d245d9f8701123ee196698c462ccbb5ff424cd533e746e85a7a329db79ccac&redirect_id=*******my_package_name******&redirect_scheme=appcenter&request_id=97fda018-869b-4f73-9a21-2884e41cca4e&platform=Android&enable_failure_redirect=true&install_id=44d98f13-9ddb-4367-82c5-0add4dc419fe"));
        List<ResolveInfo> browsers = getPackageManager().queryIntentActivities(intent, 0);
        if (browsers.isEmpty()) {
            AppCenterLog.error("test", "No browser found on device, abort login.");
        } else {

            /*
             * Check the default browser is not the picker,
             * last thing we want is app to start and suddenly asks user to pick
             * between 2 browsers without explaining why.
             */
            String defaultBrowserPackageName = null;
            String defaultBrowserClassName = null;
            ResolveInfo defaultBrowser = getPackageManager().resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY);
            if (defaultBrowser != null) {
                ActivityInfo activityInfo = defaultBrowser.activityInfo;
                defaultBrowserPackageName = activityInfo.packageName;
                defaultBrowserClassName = activityInfo.name;
                AppCenterLog.debug("test", "Default browser seems to be " + defaultBrowserPackageName + "/" + defaultBrowserClassName);
            }
            String selectedPackageName = null;
            String selectedClassName = null;
            for (ResolveInfo browser : browsers) {
                ActivityInfo activityInfo = browser.activityInfo;
                if (activityInfo.packageName.equals(defaultBrowserPackageName) && activityInfo.name.equals(defaultBrowserClassName)) {
                    selectedPackageName = defaultBrowserPackageName;
                    selectedClassName = defaultBrowserClassName;
                    AppCenterLog.debug("test", "And its not the picker.");
                    break;
                }
            }
            if (defaultBrowser != null && selectedPackageName == null) {
                AppCenterLog.debug("test", "Default browser is actually a picker...");
            }

            /* If no default browser found, pick first one we can find. */
            if (selectedPackageName == null) {
                AppCenterLog.debug("test", "Picking first browser in list.");
                ResolveInfo browser = browsers.iterator().next();
                ActivityInfo activityInfo = browser.activityInfo;
                selectedPackageName = activityInfo.packageName;
                selectedClassName = activityInfo.name;
            }

            /* Launch generic browser. */
            AppCenterLog.debug("test", "Launch browser=" + selectedPackageName + "/" + selectedClassName);
            intent.setClassName(selectedPackageName, selectedClassName);
            startActivity(intent);
        }
```

Is the crash resolved by simply doing:

```

        /* Open a browser but we don't want a chooser U.I. to pop. */
        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://install.appcenter.ms/apps/f626dbb0-bd87-46e4-9214-14d06a2fdac5/update-setup/?release_hash=23d245d9f8701123ee196698c462ccbb5ff424cd533e746e85a7a329db79ccac&redirect_id=*******my_package_name******&redirect_scheme=appcenter&request_id=97fda018-869b-4f73-9a21-2884e41cca4e&platform=Android&enable_failure_redirect=true&install_id=44d98f13-9ddb-4367-82c5-0add4dc419fe"));

        /* Launch generic browser. */
        startActivity(intent);
```

It's important that you don't select a default browser during all the tests as it was the case when you crashed.

Thanks in advance.

**Comment by luboganev** [comment]
Hi @guperrot ,
Thanks for the suggestion. I'll try this definitely.
I don't have access to that device over the weekend, so I'll be able to test again on Monday. I'll post my findings here after that.

**Comment by luboganev** [comment]
Hi everyone,

I have performed some testing with the code @guperrot provided and have found some interesting results.

### Test setup
- Phone: Sony Xperia Z1 Compact Android 5.1 (It's different device, I know, that's intentional)
- No default browser is set
- Opera is actually the only available browser on the device (I have disabled the Chrome one)

### Results
The code runs just fine and opens the Opera Browser without any issues. At second look, however, I've noticed it actually starts a completely different Activity. In the crash log I've posted above, the SDK tries to start this Activity and crashes:
`Launch browser=com.opera.browser/com.opera.browser.leanplum.LeanplumCatchActivity`

When I run the same thing on the Sony phone it actually starts the correct Launcher Activity of the Opera browser and runs just fine:
`Launch browser=com.opera.browser/com.opera.android.MainLauncherActivity`

However, if I force the code snippet to start the _LeanplumCatchActivity_ on the Sony as well, I get the same crash SecurityException. This shows, the crash itself is not caused by an OS issue of Xiaomi but is related to the Opera Browser itself and the Activities it reports when this line of the code is invoked:
`Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("*******the very long url******"));
List<ResolveInfo> browsers = activity.getPackageManager().queryIntentActivities(intent, 0);`

The list returned above contains two activities coming from the Opera Browser app as seen in the screenshot below:
![Screenshot 2019-05-20 at 09 55 48](https://user-images.githubusercontent.com/4664101/58005257-8345cd00-7ae5-11e9-8e4f-455fbd8069b7.png)

As you notice, the Activity causing the crash is also in the list, but not at the first place, so the SDK actually does not invoke it, cause it picks the first available from the list. So in the case of the Sony phone, we just get lucky due to the order of Activities in the list. I will post the results of the same test with the Xiaomi Device in a follow up comment, since I don't currently have access to the device.

**Comment by guperrot** [comment]
Hi thanks for the testing.
It's basically a permission issue that the query does not account for.

The SDK bypassed the intent picker as it would be weird for the end user to be asked what browser to use without explanation of what is going on.

Also we use this default mechanism (first in list) only if the user never ever chose a default browser on the device. It should be an edge case only for developers testing on new (or freshly reset) phones, but still need to be fixed.

The try/catch then fall back on another browser sounds like a reasonable solution.

**Comment by guperrot** [comment]
@luboganev in addition to the suggested fix, I'd like you to do 1 more test if possible, can you open any http link from the mail application (for example) and remember to use always opera when prompted to?

Once the default browser is registered, does AppCenter still crashes?

**Comment by luboganev** [comment]
Hi @guperrot , there is unfortunately more to it than just the default browser. 

### Test setup (FAIL)

The phone has the default Xiaomi Browser, Chrome and Opera installed. As you will see, none of those appears in the list of browsers obtained from the query for IntentActivities. Here's the behavior of opening a link from the mail app:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4664101/58078762-ca989000-7baf-11e9-97e8-dc7710e95d5a.gif)

As you can see, there is no issue in opening the browser from the email client. This is probably due to the fact the Email client does not care about not showing a picker and just tries to open the link like the second snippet you have provided.

Now, I have done testing of the first snippet again. The problem is **even if you have selected a default browser, the code you have provided will still crash**. This is cause by the following part of the code:
`String selectedPackageName = null;
            String selectedClassName = null;
            for (ResolveInfo browser : browsers) {
                ActivityInfo activityInfo = browser.activityInfo;
                if (activityInfo.packageName.equals(defaultBrowserPackageName) && activityInfo.name.equals(defaultBrowserClassName)) {
                    selectedPackageName = defaultBrowserPackageName;
                    selectedClassName = defaultBrowserClassName;
                    AppCenterLog.debug("test", "And its not the picker.");
                    break;
                }
            }
            if (defaultBrowser != null && selectedPackageName == null) {
                AppCenterLog.debug("test", "Default browser is actually a picker...");
            }
`

The assumption that the _default browser is a picker_ is simply not true in the case of the Xiaomi Redmi 5A. You make a very strong assumption in this code, which is that **the default browser has to be contained in the list of browsers**. However, this does not hold true for some reason on this device. Please check the following screenshots showing my debugging session and you will better understand the problem.

**Comment by guperrot** [comment]
> # Resolution suggestion
> I would like to propose that the code from the first snippet actually contains a try {} catch {} safeguard and use the second snippet as a fallback in case the first one crashes. Of course, you might think of better solution that matches better the SDK achitecture. In any case, I think it is critical to get this right, since this causes an app to crash so early, that not even the AppCenter crash reporting can send anything to the backend. If this would happen in the wild, noone will be able to see any crashes except when they start appearing in the Google Play console.

Ok I missed the fact that the list returned only invalid browsers, looks like try/catch the entire existing code and fallback to direct startActivity is the only way to work around the issue.

**Comment by luboganev** [comment]
@guperrot I see the fix was already merged to develop and it will probably be released with the next release. Should I close the issue or it is something you're going to do once the fix is released?

**Comment by guperrot** [comment]
Hi, we usually close the issue only after release for visibility and avoid duplicates.

**Comment by MatkovIvan** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
