### ISSUE TITLE
Push message without visible notification

### ISSUE THREAD

**Issue by einarvalgeirsson** [microsoft/appcenter-sdk-android#1173]
### **Description**

I'm evaluating the use of AppCenter Push but am not able to receive a push message without the SDK creating and displaying a visible notification. 
What I'd want is to be able to control if there should be a visible notification for the user or not, depending on the message content. 
Should I be using plain FCM for this and not AppCenter Push, as it seems to default to visible notifications?

**Comment by guperrot** [comment]
(ping webhook)

**Comment by guperrot** [comment]
Hi, the feature request is tracked there: https://github.com/microsoft/appcenter/issues/87.
You can upvote and subscribe to that one.

**Comment by KSemenenko** [comment]
I also need such functionality

**Comment by jwargo** [comment]
@einarvalgeirsson @KSemenenko Thank you for the feedback, we’re hearing this from many customers and it is on our roadmap.

**Comment by AnastasiaKubova** [comment]
Hi there!
The App Center Push module has been removed from App Center SDK in the [4.0.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.0.0) version so we are closing this feature request.

As an alternative to App Center Push, we recommend you migrate to [Azure Notification Hubs](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-overview) by following the [Push Migration Guide](https://docs.microsoft.com/en-us/appcenter/migration/push/).
