### ISSUE TITLE
Support DistributeListener.onNoUpdateAvailable like hockeyApp

### ISSUE THREAD

**Issue by YoungjaeKim** [microsoft/appcenter-sdk-android#1215]
### **Description**

With hockeyApp `UpdateManagerListener.onNoUpdateAvailable` listener, I gave a toast message to user when user manually clicks 'update app' button but no update existed. Without this listener, the user does not know the update request is well triggered or not.

Could you please add this feature to SDK?

### **Details**

1. Which SDK version are you using?
    - 2.2.0
2. Which OS version did you experience the issue on?
    - Android 7

**Comment by jwargo** [comment]
@YoungjaeKim thank you for bringing this to our attention, we will investigate.

**Comment by YoungjaeKim** [comment]
@jwargo Thanks. above mentioned HockeyApp listener is here; https://github.com/bitstadium/HockeySDK-Android/blob/30eafc6cdded517f06d0547e835235594e289b92/hockeysdk/src/main/java/net/hockeyapp/android/UpdateManagerListener.java#L56

**Comment by xzhu005** [comment]
We are using HockeyApp's UpdateManagerListener.onNoUpdateAvailable callback in our enterprise app as well. Any updates on this feature?

**Comment by AnastasiaKubova** [comment]
The feature has been released in version [4.1.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.1.0).
