### ISSUE TITLE
W/System.err( 6127): remove failed: ENOENT (No such file or directory) 

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/appcenter-sdk-android#1233]
During app initialization on android, before I get to the MainPage I get following error: 08-30 13:46:19.081 W/System.err( 6127): remove failed: ENOENT (No such file or directory) : /data/user/0/com.app.myapp/files/appcenter/database_large_payloads/group_analytics/10.json
After this the splashscreen stays on my screen until I kill the app, if I press pause in visual studio, I don't see any c# threads, I only see a worker thread
Not Flagged 6 0 Worker Thread System.Threading.WaitHandle.Wait_internal()
[External Code]

### **Details**

1. Which SDK version are you using?
    - 2.1.1
2. Which OS version did you experience the issue on?
    - e.g. Android 7

**Comment by Jamminroot** [comment]
Hello, @KSemenenko, thanks for getting in touch.
So far it's hard to tell what is not working as expected - can you share verbose logs with us?
Also, you seem to be using xamarin wrapper sdk, is that correct?
Which platform is it in this case - Xamarin.Forms or Xamarin Native app?
Where did you initialize AppCenter?
