### ISSUE TITLE
App Declining in app updates through app center

### ISSUE THREAD

**Issue by davidbuckleyni** [microsoft/appcenter-sdk-android#1297]
set up Microsoft update according to the app centre documentation however I am getting the following dialogue.

https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin

I am using android 9.1 i used the normal download function Steps to reproduce

1 I had to install new version on Phone so downloaded via email

2 Sent a new version to app centre for testing the below

3 Presented with that dialogue when I started the app

I places this in my OnCreate in MainActivty.cs

    AppCenter.Start("{secret key}", typeof(Distribute));
  And the following in my App.Xaml

    AppCenter.Start("android=secret-key;",
          typeof(Distribute), typeof(Distribute));
I also placed this in OnStart

Distribute.SetEnabledAsync(true);
Can someone tell me why I am getting the below dialogue
![](https://i.imgur.com/oQBh1PJ.png)

![](https://i.imgur.com/2AYl5BI.png)

**Comment by annakocheshkova** [comment]
Hi there @davidbuckleyni so you downloaded new version from e-mail, installed it, and got this dialog right? 
If so, could you share the verbose logs? They can be collected from the device normally via Logcat.

**Comment by annakocheshkova** [comment]
Hey! We haven't heard from you in a while, do you have any more updates? If so, please let us know. Thanks!

**Comment by davidbuckleyni** [comment]
Sorry accepted a new job this week so have not been on @AnastasiaKubova  this is still much an issues I have since removed the update so have been un able to provide you the logs.

Steps to reproduce

1 Install the App Using an Email
2 Donwload apk
3 Install app
4 Send a new version of the app via app center
5 Start app it detects its but then sends the below message

![image](https://user-images.githubusercontent.com/5619229/68074995-fd1ef980-fd99-11e9-9b52-562e5a7c2f2a.png)

I would love this feature as its hell for distributing updates at moment esp if have ten plus handsets.  Will their ever be real-time updates.

**Comment by guperrot** [comment]
We can't reproduce the bug with those steps are those are indeed the standard steps and work for us.

We would unfortunately need the logs and also confirm the same browser was used from the email and from the SDK.

**Comment by Jamminroot** [comment]
We haven't heard from you for a while. Are you still facing the issue?
I'm closing the issue as of now, but feel free to reopen if you face the problem with the SDK and would like our assistance.
