### ISSUE TITLE
Method to save crash and upload it to AppCenter

### ISSUE THREAD

**Issue by ronnyremesnik** [microsoft/appcenter-sdk-android#1298]
### **Description**

There is no method to save crash

In HockeyApp SDK there is an method - `ExceptionHandler.saveException`
which allows to save the exception to disk, which later get uploaded to the HockeyAppSDK

Is there an equivalent method in AppCenter SDK ?

Thanks.

**Comment by annakocheshkova** [comment]
Hi there. There's no such method in App Center SDK atm, but if you save the exception in the proper format in the proper folder, it will get sent to App Center. 
I'll mark this as a feature request.
Meanwhile, would you like me to point you to the places in code with the necessary format?

**Comment by annakocheshkova** [comment]
Also in one of the next releases we plan to support r`Crashes.trackError` API. Would that be convenient for you?

**Comment by ronnyremesnik** [comment]
Hi @annakocheshkova, Crashes.trackError will be very helpful, yes, handled errors are exactly what we need, thank you!

**Comment by annakocheshkova** [comment]
Ok cool. We will notify you once it is released.

**Comment by AnastasiaKubova** [comment]
Hi @ronnyremesnik ! The release with this API has been [released](https://github.com/microsoft/appcenter-sdk-android/releases/tag/2.5.0 ).

**Comment by nak5ive** [comment]
can we expect to see the handled errors show up in any dashboard UI? Diagnostics displays crash information, but doesn't list handled errors. What is the best way to view/search handled errors?

**Comment by guperrot** [comment]
The feature has not been enabled yet for everyone due to issues syncing SDK releases with .NET and Unity platforms as well, thus docs were on hold as well. In the meantime, you can contact us with the chat button on portal so we can enable it for you. Sorry for the inconvenience it causes.

**Comment by guperrot** [comment]
We decided to reveal the UI on the portal for everyone as the other SDKs should be released soon. Thus you don't have to contact us to get the feature enabled individually. The docs will be published some time tomorrow.

**Comment by nak5ive** [comment]
awesome. thanks!

**Comment by guperrot** [comment]
The docs for handled errors have been published at https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#handled-errors.
