### ISSUE TITLE
Appstore

### ISSUE THREAD

**Issue by Asmatmaker** [microsoft/appcenter-sdk-android#1311]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guperrot** [comment]
Hi, please update title and edit the description so that we know what feature you are requesting (the default template was not edited so it contains only placeholders right now and the title is not descriptive enough).

I am closing in the meantime, feel free to reopen after editing.
