### ISSUE TITLE
HockeyApp SDK app does not find new releases with AppCenter SDK of the same app

### ISSUE THREAD

**Issue by anchuste** [microsoft/appcenter-sdk-android#1312]
We have moved our Hockey App site to App center. We have tested the features using app center and everything works fine. We are trying to release a new version 2.0.0 that have the App Center SDK changes. But when we search for updates in version 1.0.0 that uses Hockey SDK, it is not finding the new release

How can we move from Hockey App SDK to App Cnter SDK using the distribution feature and not disturbing the users?

**Comment by anchuste** [comment]
More details:

I have installed the app on my device (your app 1.0.0 ( which HockeyApp SDK) installed) now I have done a new release of your app 2.0.0 (AppCenter sdk), so i am not getting an update popup for the new release.

**Comment by AnastasiaKubova** [comment]
Hi, @anchuste ! Thanks for getting in touch with us!
You should upload this build to HockeyApp as well so that the update prompt shows up.

**Comment by anchuste** [comment]
Do you refer to the HockeyApp repository? Portal Web HockeyApp is not accessible it drives me to AppCenter. So I have only access to AppCenter.

**Comment by AnastasiaKubova** [comment]
You can return to Hockey App through this or go to hockeyapp and login normally.
![image](https://user-images.githubusercontent.com/42138465/68386736-b8b2a580-016d-11ea-8d17-474cc3b3fde3.png)

**Comment by anchuste** [comment]
@AnastasiaKubova Thas is a image, could you pass me the link?

**Comment by AnastasiaKubova** [comment]
@anchuste please go to the [Hockey App](https://hockeyapp.net/)  and push `Log In`

**Comment by anchuste** [comment]
@AnastasiaKubova i did that, when i select my app, HockeyApp drives me automatically to AppCenter, because i migrated it.

**Comment by AnastasiaKubova** [comment]
@anchuste could you please clarify some details:
- Is your app public or private on HA?
- Does your app use auth?

**Comment by anchuste** [comment]
We already fixed the problem.  The reason was that we were distributing the new release to a different group distribution. Thank you for your support!
