### ISSUE TITLE
Veracode Flaw CWE ID 117 Improper Output Neutralization for Logs

### ISSUE THREAD

**Issue by rajeshwarig** [microsoft/appcenter-sdk-android#1314]
### **Description**

We use the App Center SDK within our Android app. During the Veracode security scans run on the builds, there were 9 security policy violations or flaws reported for App Center. This issue lists 2 flaws that were reported under the Veracode CWE ID 117. 

Details for this flaw can be found here: http://cwe.mitre.org/data/definitions/117.html. 

This flaw was identified in line numbers 67 and 93 in AppCenterLog.java. A screenshot of the flaw listing in Veracode is attached.

![image](https://user-images.githubusercontent.com/1268271/68486643-848fc100-020f-11ea-877f-2fc345117f48.png)

Other Veracode flaws are reported in the following issues:
#1315 
#1316 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Run Veracode scan to the codebase.

### **Details**

1. Which SDK version are you using?
    - 2.3.0
2. Which OS version did you experience the issue on?
    - N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -N/A
4. What third party libraries are you using?
    - N/A
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here: N/A

**Comment by guperrot** [comment]
We use AppCenterLog only with our own debug and error messages for troubleshooting, AppCenterLog is not used from untrusted sources and is also disabled by default in release builds (the log level is Off by default and is an optin for troubleshooting SDK integration).

Thus this is a false positive.

**Comment by rajeshwarig** [comment]
I'm not sure I understand why if this is disabled by default in the release builds then why is it getting flagged by Veracode when we scan our builds which are all release builds?

**Comment by guperrot** [comment]
Hi, probably because you use static code analysis tool that can probably not evaluate this.
Most tools will simply look at the code and make assumptions without executing it which here would be required to know that the logs are not enabled.

**Comment by rajeshwarig** [comment]
Ok, thanks!

**Comment by guperrot** [comment]
Will now proceed to close this as the questions were answered. You can reopen if you have follow-up questions.
