### ISSUE TITLE
Veracode Flaw CWE ID 297 Improper Validation of Certificate with Host Mismatch

### ISSUE THREAD

**Issue by rajeshwarig** [microsoft/appcenter-sdk-android#1316]
### **Description**

We use the App Center SDK within our Android app. During the Veracode security scans run on the builds, there were 9 security policy violations or flaws reported for App Center. This issue lists 5 flaws that were reported under the Veracode CWE ID 297. 

Details for this flaw can be found here: http://cwe.mitre.org/data/definitions/297.html. 

This flaw was identified in line numbers 87, 92, 97, 102, 107 in TLS1_2SocketFactory.java. A screenshot of the flaw listing in Veracode is attached.

![image](https://user-images.githubusercontent.com/1268271/68489067-5c569100-0214-11ea-84fe-d37298a85b36.png)

Other Veracode flaws are reported in the following issues:
https://github.com/microsoft/appcenter-sdk-android/issues/1314
https://github.com/microsoft/appcenter-sdk-android/issues/1315

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Run Veracode scan to the codebase.

### **Details**

1. Which SDK version are you using?
    - 2.3.0
2. Which OS version did you experience the issue on?
    - N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -N/A
4. What third party libraries are you using?
    - N/A
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here: N/A

**Comment by guperrot** [comment]
This is a false positive, this code is not related to validation of the certificate.
It's an [Adapter](https://en.wikipedia.org/wiki/Adapter_pattern) for the real socket factory from Android, we are just this class to enable TLS 1.2 on Android 4.x and then all other methods are delegated to the original implementation, we just forward the calls.

You can see the code at https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter/src/main/java/com/microsoft/appcenter/http/TLS1_2SocketFactory.java.

**Comment by guperrot** [comment]
Hi, closing this as this was answered and not hearing back. Feel free to reopen if you have follow-up questions.
