### ISSUE TITLE
Updating the app via hockeyapp

### ISSUE THREAD

**Issue by kmspop** [microsoft/appcenter-sdk-android#1317]
Hi.

I have an issue with in-app update with Hockeyapp Android SDK (5.2.0)
When requesting an update check via Hockeyapp SDK, it correctly finds the latest version uploaded in the AppCenter and shows the release notes of that version. Everything seems OK.
Also the release date shown is correct as well.
When I hit Update button, it grabs the latest APK from Hockeyapp, not AppCenter.
Installation happens, app gets launched, and the app is still on the same version as before.

These are steps happening in sequence.
Version 12 is the latest build in hockeyapp.
Version 14 is the latest build in AppCenter.
User is on the old app (version 12) running hockeyapp SDK.

1. Perform update check using hockeyapp.
2. Shows new version is available (app version 14)
3. Confirms update and proceed
4. APK (version 12) gets downloaded and installation happens.
5. App launches, the user is still in version 12
6. Perform update check again and new version is available (goes to step2)

This goes on and on forever.
The app is not fully migrated over to AppCenter yet and currently being synced with hockeyapp.
I have tried changing app visibility settings from private to public. Didn't have any effect on this.
Distribution groups on both sides, hockeyapp and Appcenter, are equal. (Appcenter clearly shows that the distribution group has been automatically copied over from hockeyapp)

1. Which SDK version are you using?
    - Hockeyapp Android SDK (5.2.0) on the latest app customers are currently running
    - AppCenter Android SDK (2.5.0) on the latest app uploaded to AppCenter
2. Which OS version did you experience the issue on?
    - Android 6-9 (all versions)
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Samsung Galaxy S8, S9+, emulators
4. What third party libraries are you using?
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

Appcenter logs are not available since this is an issue with upgrade path using HockeyApp.

**Comment by anchuste** [comment]
Hello @kmspop, did you move your app to App Center? You have to do this first and then you will not have access to hockey app portal web, it drives you to App Center portal, and you will see all releases (including hockeyApp).

https://docs.microsoft.com/es-es/appcenter/transition/
 "Move your apps to AppCenter"

**Comment by nicolasguenther** [comment]
I experience the exact same problem. In my case the app is on app center. Users using an old version (distributed by hockey app) cannot update to the latest version distributed with app center.

**Comment by kmspop** [comment]
@anchuste I haven't fully moved over yet. When I try to do that in the app center, it gives me this warning
"Make sure to update to the new App Center API. The HockeyApp API will be unavailable for this app once moved."

I wasn't sure if this meant that all existing customers out there on old builds won't be able to use hockeyapp API to upgrade to builds in AppCenter.

**Comment by anchuste** [comment]
@kmspop  I can not be sure of that! But i moved my app to AppCenter (via web), and our users can do in-update automatically from app HockeyApp  to app AppCenter. 

Example:
Updating from 
APP 1.0.0 (Hockey SDK) to 
APP 1.0.1 (App Center SDK same application in the same repository) works correctly!

**Comment by Jamminroot** [comment]
Hey, @kmspop, in general, @anchuste's migration should work fine.
For more details, please follow migration guidelines, starting at where @anchuste pointed out in [his comment](https://github.com/microsoft/appcenter-sdk-android/issues/1317/#issuecomment-553776355) : https://docs.microsoft.com/es-es/appcenter/transition/
**After** you moved your applications from HA to AC portal, you can proceed to replace HA SDK with AC SDK as described here : https://docs.microsoft.com/es-es/appcenter/transition/android-sdk-migration

**Comment by nicolasguenther** [comment]
I followed the guidelines and still experience an error in the update process. Lets use anchuste's example: version 1.0.0 is using hockey sdk and version 1.0.1 is using app center sdk. When i start the app on a phone where version 1.0.0 is still installed i observe the following behavior:

1. HockeyApp update dialog pops up
2. Click "show update"
3. Update view pops up. Newest version (1.0.1) is proposed
4. Click "update" 
5. New version gets downloaded

I would expect the downloaded version to be installed. Instead the update view from step 3 pops up again. A click on "update" leads to a new download and so on. I verified that the new version of the app was indeed succesfully downloaded with a file manager. But the installation step doesn't work.

I think this is the same behavior @ksmpop described in the initial post.

**Comment by anchuste** [comment]
@nicolasguenther I think that is a bug of the app center SDK in earlier versions. Please update your SDK version to 2.5.0

Take a look at: 
https://github.com/microsoft/appcenter-sdk-android/releases
(Version 2.5.0)

**Comment by nicolasguenther** [comment]
@anchuste Thanks, but i am already using version 2.5.0

**Comment by anchuste** [comment]
Okk, it sounded like the bug that they fixed in SDK 2.5.0.

**Comment by kmspop** [comment]
It is an issue with old app updating via hockeyapp, so I don't think Appcenter SDK plays any role here.

**Comment by nicolasguenther** [comment]
@kmspop Yes, but it should be noted that updating with hockeyapp never was a problem. But now that i moved the app to appcenter it doesn't work anymore.

**Comment by anchuste** [comment]
@nicolasguenther Are you distribute app to the same group than hockeyapp? It should be exactly the same group you used to in HockeyApp.

**Comment by nicolasguenther** [comment]
I distributed the app to the same group as hockeyapp did. In my case this is the autogenerated All-users-of-x group.

**Comment by kmspop** [comment]
ok. After fully migrating over to AppCenter, I was able to update our old apps running hockeyapp SDK to the new app deployed in AppCenter.
My problem is resolved.

**Comment by russelarms** [comment]
Glad to hear that, I'm closing the issue now.
