### ISSUE TITLE
In-App Updates  AppCenterSDK and browser infinit loop

### ISSUE THREAD

**Issue by ruieduardosoares** [microsoft/appcenter-sdk-android#1318]
### **Description**

Our apps are already migrated to AppCenter and they are working fine as far as i know.
But we have experienced **some times** one issue when making a fresh installation the app 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install apk in device
2. Open app and wait for the browser to open to setup the in app updates

### **Details**

1. Which SDK version are you using?
    - 2.2.0
2. Which OS version did you experience the issue on?
    - Android 8.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Emulator Nexus 5x
4. What third party libraries are you using?
     ?
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

I will send the logs to the developer that will work on this issue because the logs have sensitive information i think.

But the issue in here it that a field called **requestId** is **invalid** and the sdk ignores, doesnt save the redirect information and starts again by opening the browser, and it does this multiple times.
I think the **requestId** that is saved in the **AppCenterSdk Shared preferences** is never equals to the ones that are going in the requests.

**This happens only a few times in fresh instalations**

**Comment by Jamminroot** [comment]
Hey, @ruieduardosoares, sorry to hear that. Is there a chance to check whether updating to latest SDK version solves the issue? There has been decent amount of work done on Distribute module lately.

**Comment by ruieduardosoares** [comment]
Hey @Jamminroot.
Thanks for the reply :+1: 
Will do that, then a will give some feedback to this issue.

**Comment by jeremyeaton89** [comment]
Some of my users were reporting this coming from a Hockeyapp SDK powered app, installing the AppCenter powered app via in-app update, and seeing infinite prompt to update the same app. Haven't been able to reproduce myself, though. 

Hockeyapp SDK Version 5.0.0

appcenter-analytics: 2.5.0
appcenter-crashes: 2.5.0
appcenter-distribute: 2.5.0

**Comment by russelarms** [comment]
@ruieduardosoares have you resolved your issue?

@jeremyeaton89 thanks for reporting this. Is there any chance to provide [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level) for that case?

**Comment by jeremyeaton89** [comment]
@russelarms i haven't been able to reproduce it myself, so no logs, sorry.

**Comment by andrekiba** [comment]
Same problem here. We want to know about updates not only when the app is restarted but also when goes in background and then comes back on foreground. To do this we use the trick that disables and then re-anables the Distribute. I have this code inside the OnResume of the MainActivity (XamarinForms). The problem occurs during the first launch when the app needs to open Chrome to register the cookie. Is there a way to solve this problem? Is there a way to know if the app has already completed the link procedure with Chrome?

**Comment by ruieduardosoares** [comment]
> @ruieduardosoares have you resolved your issue?
> 
> @jeremyeaton89 thanks for reporting this. Is there any chance to provide [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level) for that case?

I still havent do anything yet, but there is a new version of the Appcenter SDK: 2.5.0.
I need to first find a way to explicitly reproduce the error since this doesnt always happen.

**Comment by annakocheshkova** [comment]
Hey @ruieduardosoares we haven't heard from you in a while. I'm closing this issue for now, feel free to re-open if you have more info!
