### ISSUE TITLE
No In-App updates for public app without AppCenter account

### ISSUE THREAD

**Issue by stefanoberdoerfer** [microsoft/appcenter-sdk-android#1322]
### **Description**

It is currently impossible to continue showing the In-App update dialog for our publicly distributed app without the user being prompted for an AppCenter account. Does a user without an AppCenter account have to download every update manually via the public download link? With HockeyApp there was no need for an account in order to show the In-App updates for public apps. 

### **Repro Steps**

1. Create an AppCenter application with distributiongroup "AllUsers" and a public download link
2. Integrate AppCenter android sdk and enable distribution
3. On app startup the user is always prompted for an AppCenter account via browser

### **Details**

1. Which SDK version are you using?
    - 2.5.0
2. Which OS version did you experience the issue on?
    - e.g. Android 6.0.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Trimble TDC100 WiFi physical device

**Comment by russelarms** [comment]
Hi @stefanoberdoerfer, thanks for reaching out!
AppCenter recently disabled the requirement to log in under AppCenter account for public releases, so it should work without any dialogs.
Could you please double-check that it doesn't work? If so, can I ask you to file a support ticket with us so we can look into your specific issues and logs? 
https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us

**Comment by stefanoberdoerfer** [comment]
Thanks for the fast response. I've recorded the following logs when starting the app. The sdk is still automatically opening the browser every time the app is started.
[device_logs.txt](https://github.com/microsoft/appcenter-sdk-android/files/3868087/device_logs.txt) (I removed the plaintext App-Secret from the logs)

**Comment by fabiendem** [comment]
@stefanoberdoerfer I think `InstallerPackageName=null` suggests that you installed the app via `adb`.
Have you tried installing the app from the AppCenter page instead?

**Comment by stefanoberdoerfer** [comment]
Ok now the app launches the browser and I can return to the app without logging into an AppCenter account. Thank you for the help. I think this should be documented for other developers. It's a bit of a hassle in the development process that the update mechanism can't be tested properly for this case when installing the app from IDE.

**Comment by fabiendem** [comment]
> I think this should be documented for other developers. It's a bit of a hassle in the development process that the update mechanism can't be tested properly for this case when installing the app from IDE.

True, I have been bitten by this before as well.
It's mentioned in the doc (https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#how-do-in-app-updates-work):
> When each user opens the link in their email, the application will be installed on their device. It's important that they use the email link to install - we do not support side-loading.

But I don't think it's obvious to everyone what "side-loading" refers to.
It would be helpful to mention "Do not use adb or Android Studio".

And maybe explain "why". (I think it's because some App Stores have a `InstallerPackageName=null` as well so AppCenter cannot take the risk, but I am speculating..)

**Comment by guperrot** [comment]
Actually InstallerPackageName=null is not related to side-loading, this flag is used to disable in-app updates for store builds such as Play Store (it will also be null if you install it from AppCenter portal or sometimes have a value that does not correspond to a real store).

Side loading indeed means not installed by App Center portal in this context (more specifically not downloaded from App Center). The documentation will be updated.

**Comment by russelarms** [comment]
Since we've updated the docs, I think the issue can be closed now.
Feel free to open it if you have any more questions regarding this problem.
