### ISSUE TITLE
Dialog saying that the app was side-loaded even though it was downloaded via the App Center app

### ISSUE THREAD

**Issue by mcezat** [microsoft/appcenter-sdk-android#1326]
Our app was originally in HockeyApp and we recently migrated to App Center. In the first build that used the App Center SDK, even though a user logs in with their App Center account that's included in the distribution group for updates, users see the following dialog after being taken back to the app:

![Screenshot_20191122-164058](https://user-images.githubusercontent.com/15025474/69466713-d3c70d00-0d4a-11ea-9882-c38436d26d2f.jpg)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Download and install an older version of app that uses the App Center SDK from the update email.
2. Launch the app.
3. User is taken to a web page to either sign into their App Center account for the first time OR if they are already signed in, they see a page that says "In-app updates enabled! Returning to app...".
4. User is taken back to the app and the "in-app updates disabled" dialog (attached) is seen.

### **Details**

1. Which SDK version are you using?
2.5.0
2. Which OS version did you experience the issue on?
Android 6, 9, 10
3. What device version did you see this error on?  Were you using an emulator or a physical device?
OnePlus 7t, OnePlus 6t, Google Pixel 3a, Revvlry, Samsung Galaxy S6
4. What third party libraries are you using?
Airship, Adobe MobileCore
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
Will supply logs privately.

**Comment by MatkovIvan** [comment]
Hi @mcezat ,

The logs are required for understanding what's going wrong. If you want to share it privately, please open the support ticket (blue button in the right-bottom corner) on the portal.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
