### ISSUE TITLE
android.os.RemoteException

### ISSUE THREAD

**Issue by rameshvoltella** [microsoft/appcenter-sdk-android#1327]
### **Description**
Hi  i am getting the following  crash for app center ,i dont know how to reproduce
> android.os.RemoteException: Remote stack trace: at com.android.server.am.ActivityManagerService.isTopOfTask(ActivityManagerService.java:15077) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2341) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3375) at android.os.Binder.execTransact(Binder.java:733) 

### **Repro Steps**

Please list the steps used to reproduce your issue.
Dont know how to reproduce.

### **Details**

1. Which SDK version are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - e.g. Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Redmi 7

**Comment by MatkovIvan** [comment]
Hi @rameshvoltella,

Thanks for getting in touch!
Could you please share full "raw" report (it can be downloaded from the portal)?
For now, I don't see how this exception is related to the SDK.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.

**Comment by albilaga** [comment]
Hi @MatkovIvan we have this issue and it is only happening on android 9 and the same issue. we can't reproduce it. Here is the raw file but I am also not really sure if appcenter really cause this issue
[raw.json](https://github.com/microsoft/appcenter-sdk-android/files/14063431/raw.json)
