### ISSUE TITLE
No reports on online dashboard

### ISSUE THREAD

**Issue by LeMimit** [microsoft/appcenter-sdk-android#1337]
### **Description**

I do not see Diagnostics and custom events in my dashboard.

I got the following log flow but I do not see anything in the dedicated dasboard.

![image](https://user-images.githubusercontent.com/10245195/70454178-4f92ba80-1aaa-11ea-93dc-d5bec85b8526.png)

![image](https://user-images.githubusercontent.com/10245195/70454259-6d601f80-1aaa-11ea-9cc1-8782bad0407d.png)

![image](https://user-images.githubusercontent.com/10245195/70454272-73560080-1aaa-11ea-9824-383b743b89ee.png)

### **Details**

1. Which SDK version are you using?
    - 2.5.0
2. Which OS version did you experience the issue on?
    - Android 9.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - One PLus 6 - physical

**Comment by AnastasiaKubova** [comment]
Hi, @LeMimit ! Thanks for getting in touch!
Could you please share the verbose [logs]( https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level)?

**Comment by AnastasiaKubova** [comment]
@LeMimit we haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
