### ISSUE TITLE
Breakpad crash symbolication broken?

### ISSUE THREAD

**Issue by amattila** [microsoft/appcenter-sdk-android#1338]
Something is wrong with the ndk/breakpad crash-symbolication service. It has stopped symbolicating crashes. Also, when there are symbols missing, and you click ignore, they won't appear unsymbolicated to the Issues page anymore. Even after waiting multiple hours.

Please check.

**Comment by MatkovIvan** [comment]
Hi @amattila,

Thanks for getting in touch!
Crashes are symbolicated on the backend, not by this SDK.
As mentioned in the issue template, we are using this issue tracker on GitHub only for client SDK bugs. Please open an intercom support ticket (blue chat button on the portal) for backend problems.
I'm going to close this issue now. If you think that this is the problem with this SDK - feel free to reopen it (please fill the issue template).
