### ISSUE TITLE
No Logging -> 'Cannot find Array on JSONStringer'

### ISSUE THREAD

**Issue by xrabohrok** [microsoft/appcenter-sdk-android#1340]
### **Description**

Problem was detected due to lack of any logging whatsoever on console.  This is the primary outcome that needs to be fixed (may be related to #1337 ?)

Debug builds are not exhibiting this behaviour.

After some tooling around, we discovered that turning on minification through ProGuard triggers the behavior.  Turning on ProGuard in Debug produces the following error on app startup.

`2019-12-11 14:49:50.254 8078-8132/com.XXXXXX.XXXXXX.cert E/AndroidRuntime: FATAL EXCEPTION: AppCenter.Looper
    Process: com.XXXXXX.XXXXXX.cert, PID: 8078
    java.lang.NoSuchMethodError: No virtual method array()Lorg/json/f; in class Lorg/json/f; or its super classes (declaration of 'org.json.f' appears in /data/app/com.XXXXXX.XXXXXX.cert-ykN8G_a_eGsO1CRMsy8_KQ==/base.apk)
        at com.microsoft.appcenter.utils.context.AuthTokenContext.serializeHistory(AuthTokenContext.java:397)
        at com.microsoft.appcenter.utils.context.AuthTokenContext.setHistory(AuthTokenContext.java:384)
        at com.microsoft.appcenter.utils.context.AuthTokenContext.addTokenHistory(AuthTokenContext.java:225)
        at com.microsoft.appcenter.utils.context.AuthTokenContext.setAuthToken(AuthTokenContext.java:163)
        at com.microsoft.appcenter.utils.context.AuthTokenContext.finishInitialization(AuthTokenContext.java:146)
        at com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:961)
        at com.microsoft.appcenter.AppCenter.access$700(AppCenter.java:60)
        at com.microsoft.appcenter.AppCenter$8.run(AppCenter.java:871)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
`

The obfuscated thing that is supposed to have array is `JSONStringer`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Turn on Proguard Minification for your current build flavor
2. Build
3. Launch the app

### **Details**

1. Which SDK version are you using?
    1.5.1
2. Which OS version did you experience the issue on?
    everything, but tested with Android 9 (API 28)
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Everything, but log is from an emulated Pixel 3 with Android 9
4. What third party libraries are you using?

- AndroidX
- Retrofit2
- Square: Picasso
- appsflyer
- Adobe
  - Marketing
  - Targets
- ThreetenBP
- Koin
   
  
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

see above, surrounding lines seem irrelevant, but more can be provided upon request

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch!
How I see from your report you use the 1.5.1 version of App Center. Could you please try to update App Center to the [latest version](https://github.com/microsoft/appcenter-sdk-android/releases/tag/2.5.1) and try to reproduce this issue. Please, let me know about the result.

**Comment by xrabohrok** [comment]
Sorry, that was a typo on my part.  We were originally on 1.7.0, then this issue prompted us to update to 2.5.1, and that has not fixed this issue.

**Comment by AnastasiaKubova** [comment]
@xrabohrok, I tried to reproduce your issue but it works right for me. Does your project have some specific configuration I should know about?

**Comment by xrabohrok** [comment]
Do you want to see our Proguard rules maybe?  This feels very much like a tree shake gone wrong...

```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile


-keep class retrofit.** { *; }
-keepattributes SourceFile,LineNumberTable
-keep class * extends java.util.ListResourceBundle {
    protected Object[][] getContents();
}

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
}

-keepnames class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

-keepclassmembernames interface * {
    @retrofit.http.* <methods>;
}



#reactiveX
-keep class io.reactivex.Observable {*; }

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}


-dontwarn com.google.android.gms.**

-dontwarn com.google.firebase.iid.**

-keep public class * implements java.io.Serializable {*;}

#AndroidX
-dontwarn androidx.**
-keep class androidx.** { *; }
-keep interface androidx.** { *; }
#Support v4
-dontwarn android.support.v4.**
-keep class android.support.v4.** { *; }
#Support v7
-dontwarn android.support.v7.**
-keep class android.support.v7.** { *; }

##Lambdas
-dontwarn java.lang.invoke.*
-dontwarn **$$Lambda$*

#Material Design
-dontwarn com.google.android.material.**
-keep class com.google.android.material.** { *; }

#-dontwarn rx.**

### Retrofit 2
# Platform calls Class.forName on types which do not exist on Android to determine platform.
-dontnote retrofit2.Platform
# Platform used when running on RoboVM on iOS. Will not be used at runtime.
-dontnote retrofit2.Platform$IOS$MainThreadExecutor
# Platform used when running on Java 8 VMs. Will not be used at runtime.
-dontwarn retrofit2.Platform$Java8
# Retain generic type information for use by reflection by converters and adapters.
-keepattributes Signature
# Retain declared checked exceptions for use by a Proxy instance.
-keepattributes Exceptions

-dontwarn retrofit2.adapter.rxjava.CompletableHelper$**
#To use Single instead of Observable in Retrofit interface
-keepnames class rx.Single
#Retrofit does reflection on generic parameters. InnerClasses is required to use Signature and
# EnclosingMethod is required to use InnerClasses.
-keepattributes Signature, InnerClasses, EnclosingMethod
# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**
# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit
# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.-KotlinExtensions

# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

###-------------------------------
### OkHttp3
###-------------------------------
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn okhttp3.internal.platform.*
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

###-------------------------------
### Reactive Network
###-------------------------------
-dontwarn io.reactivex.functions.Function
-dontwarn rx.internal.util.**
-dontwarn sun.misc.Unsafe

###-------------------------------
### RxJava, RxAndroid
###-------------------------------
-keep class rx.schedulers.Schedulers {
    public static <methods>;
}
-keep class rx.schedulers.ImmediateScheduler {
    public <methods>;
}
-keep class rx.schedulers.TestScheduler {
    public <methods>;
}
-keep class rx.schedulers.Schedulers {
    public static ** test();
}
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
    long producerIndex;
    long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    long producerNode;
    long consumerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
-dontnote rx.internal.util.PlatformDependent
-keepnames class rx.Observable

###-------------------------------
### Others
###-------------------------------
-dontwarn java.util.concurrent.**
-dontwarn sun.misc.**

```

**Comment by annakocheshkova** [comment]
Hi @xrabohrok, I've seen similar issue not long time ago on SO, is it possible that this is related to [build.gradle version](https://stackoverflow.com/a/57893238/7453375)?

**Comment by xrabohrok** [comment]
I bumped gradle up to 3.5.3 and that did not fix it

**Comment by guperrot** [comment]
Would adding this rule to your application's proguard.cfg help?
```
-keepclassmembers org.json.JSONStringer {
    public JSONStringer array();
}
```

**Comment by guperrot** [comment]
The issue was resolved on another support channel.
Turns out needed ` -keep class org.json.** {*;}` in that application.

**Comment by xrabohrok** [comment]
It took a while to confirm, but we used our own version of the same ProGuard rules to exclude the Json library from modification.  What also works is using a non-canonical Json library, as it also dodges ProGuard.
