### ISSUE TITLE
Distribute not calling onReleaseAvailable

### ISSUE THREAD

**Issue by rwrife** [microsoft/appcenter-sdk-android#1374]
I've setup my Android app like:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    Distribute.setListener(this);
    Distribute.setEnabled(true);
    Distribute.setEnabledForDebuggableBuild(true);
    // not sure if this will work beyond the production release
    Distribute.setUpdateTrack(UpdateTrack.PRIVATE);
    AppCenter.start(getApplication(), appCenterKey, Distribute.class);
}
@Override
public boolean onReleaseAvailable(Activity activity, ReleaseDetails releaseDetails) {
    String versionName = releaseDetails.getShortVersion();
    int versionCode = releaseDetails.getVersion();
    String releaseNotes = releaseDetails.getReleaseNotes();
    Uri releaseNotesUrl = releaseDetails.getReleaseNotesUrl();
    AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(activity);
    dialogBuilder.setTitle("Version " + versionName + " available!");
    dialogBuilder.setMessage(releaseNotes);
}
```
My activity implements the DistributeListener interface and seems to detect a new distribution, but doesn't actually call the onReleaseAvailable and instead just launches the browser.  Any ideas?

**Comment by Jamminroot** [comment]
Hello, is that a sideloaded build? As in - at a time when new release is detected, was application initially installed through portal? Because setting track to private requires authorization on portal, and this might force browser to start up.
Otherwise, can you provide verbose logs?

**Comment by rwrife** [comment]
Some additional background that may be the issue, so this is a React Native application that does have AppCenter ReactNative SDK wired up, in addition to the Distribute SDK wired up separately on the native side.  In my test above it was via the IDE in debug, so yes it was technically side loaded.  I did try to do a full adhoc release through AppCenter but I get the same results.

Also I randomly (maybe not that random) get this webpage instead of the download site 
![image](https://user-images.githubusercontent.com/1685329/75275613-abbbcf80-57b9-11ea-8cd4-44ae7c2f029e.png)  

I'll get the verbose logs and attach them as well.

**Comment by Jamminroot** [comment]
Have you considered using React-Native SDK?

**Comment by fabiendem** [comment]
The React Native SDK doesn't support Distribute :/

**Comment by Jamminroot** [comment]
My bad, sorry, completely forgot that its just the Distribute in the ticket.
Please give us some time to look deeper into it

**Comment by Jamminroot** [comment]
Do you have RN SDK implemented alongside, on the RN layer?

**Comment by Jamminroot** [comment]
Unfortunatelly, aside from suggesting using CodePush (if no native layer updates are required), I can't offer much, since we do not officially support this type of usage scenarios.
Here's a [link](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/) to CodePush just in case.

**Comment by Jamminroot** [comment]
We've made a small investigation. There's 2 points:
1. You seem to not return any value.
1. You seem to not show update dialogue. 
Here's an example:
https://github.com/microsoft/appcenter-sdk-android/blob/develop/apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchDistributeListener.java#L21
For this, assume `custom==true`

**Comment by Jamminroot** [comment]
Since that is not officially supported scenario, I'm closing the issue, but have you any further questions - please respond in a thread, we would see that.
