### ISSUE TITLE
save Attachments before crashing

### ISSUE THREAD

**Issue by JosebaRuizO** [microsoft/appcenter-sdk-android#1397]
**Is your feature request related to a problem? Please describe.**
I've been testing the sdk and I'd like to share a question with all of you:
As far as I understood, the ErrorReport is storaged when the app crashes. The ErrorAttachments are get when the app restarts and just before sending the reports to the cloud. Then, both are sent together.
**Describe the solution you'd like**
I believe to save the attachments at the time of saving the report makes much more easy to save specific data/logs of the specific status of the app before crashing. 
As far as I know, HockeySDK  saves everything at the same time.

 Is it possible to have already the solution that I describe with AppCenter and am I misleading something?

Thank you so much.

**Comment by russelarms** [comment]
Hi, thanks for reaching out!
Having a callback in a time of a crash can be unreliable for the SDK.

>The ErrorAttachments are get when the app restarts and just before sending the reports to the cloud

Yes, but you can save them anytime you want.
I believe a possible solution would be to add another [UncaughtExceptionHandler](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.UncaughtExceptionHandler.html) after the SDK initialized and try to save the required info there. But it needs to be checked.

**Comment by JosebaRuizO** [comment]
Hello @russelarms 
Thank you so much for your reply.

I believe that wasn't that harmfull as it was donde in hockeysdk. Saving the extra info from the listener at the same time you save the crash info. That's why I thought that could be work in same way.
To implement another uncaughtexceptionhandler I think it makes conflict with the one it's already implemented.

Extracted from ExceptionHandler class on HockeySDK   
```
 crashDetails.writeCrashReport(context);
        if (listener != null) {
            try {
                writeValueToFile(context, limitedString(listener.getUserID()), filename + ".user");
                writeValueToFile(context, limitedString(listener.getContact()), filename + ".contact");
                writeValueToFile(context, listener.getDescription(), filename + ".description");
            } catch (IOException e) {
                HockeyLog.error("Error saving crash meta data!", e);
            }
```

**Comment by MatkovIvan** [comment]
Hi @JosebaRuizO ,

I see that you are looking for a way to attach user id (based on shared code snippet). To do this, you can just use [`AppCenter.setUserId`](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#identify-users) for user id. It will be included to report by SDK.

**Comment by JosebaRuizO** [comment]
Hi @MatkovIvan ,

Thanks!
Yes, I'm using that method too. But I'd like to save a file with the last screen used before the crash.
The problem is just to save it before the app restarts. As the other SDK does, my question was if it could be implemented in a similar way.

**Comment by russelarms** [comment]
As a workaround that I mentioned earlier you can use a simplified analog of AppCenter's [UncaughExceptionHandler](https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/UncaughtExceptionHandler.java):
```
class UncaughtExceptionHandlerCustom implements Thread.UncaughtExceptionHandler {

    private Thread.UncaughtExceptionHandler mDefaultUncaughtExceptionHandler;

    private Context context;

    UncaughtExceptionHandlerCustom(Context context) {
        this.context = context;
    }

    @Override
    public void uncaughtException(Thread thread, Throwable exception) {
        writeValueToFile(context, limitedString(listener.getUserID()), filename + ".user");
        writeValueToFile(context, limitedString(listener.getContact()), filename + ".contact");
        writeValueToFile(context, listener.getDescription(), filename + ".description");
        
        //mDefaultUncaughtExceptionHandler is com.microsoft.appcenter.crashes.UncaughtExceptionHandler here
         mDefaultUncaughtExceptionHandler.uncaughtException(thread, exception);
    }

    void register() {
        mDefaultUncaughtExceptionHandler = Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler(this);
    }
}
```
The main idea is to register it **after** the Crashes module is enabled, so your custom handler can pass exception further on the chain:
```
Crashes.isEnabled().thenAccept(new AppCenterConsumer<Boolean>() {
     @Override
     public void accept(Boolean isEnabled) {
         if (isEnabled){
              new UncaughtExceptionHandlerCustom(MainActivity.this).register();
         }
     }
});
```

**Comment by JosebaRuizO** [comment]
Thank you so much guys, you were really kind and helpful. It's working now.
