### ISSUE TITLE
Port to a non-Android, generic Java SDK

### ISSUE THREAD

**Issue by brunoborges** [microsoft/appcenter-sdk-android#1407]
We have a Java desktop application we'd like to add telemetry into, but this library is of no use since it depends heavily on Android APIs.

Any chance to decouple?

**Comment by annakocheshkova** [comment]
Hey @brunoborges I don't think that would be possible. Our SDK heavily relies not only on android context, but also on the application lifecycle, device info and network state in android. 
Also Distribute module requires context to show update dialog and Push module depends on Broadcast receiver which is also android thing.

**Comment by brunoborges** [comment]
What would be the recommended way to integrate Java desktop apps with 1DS then, for telemetry?

**Comment by annakocheshkova** [comment]
There's a cross-platform C++ SDK you can use through JNI in Java: [CPP Client](https://github.com/microsoft/cpp_client_telemetry/issues/new/choose).  
If there are any issues, you can open a support ticket in their repo - but as we're not quite the right place to discuss it, I'm closing this ticket.
