### ISSUE TITLE
In-app update not working properly when there is more than one Activity (Android)

### ISSUE THREAD

**Issue by adriatikgashi** [microsoft/appcenter-sdk-android#1410]
### **Description**
I'm trying to use the in-app update feature. The app has more than one activity (pretty normal stuff). I initialize the framework on the SplashActivity and after some delay it transitions to a LoginActivity. That seems to break the update flow, when this happens the download Dialog is shown, but it then gets stuck in a loop, it always shows the "install" dialog. I tried getting rid of the second Activity and then it works! The first dialog shows up (the Download Dialog) and it automatically installs the app.

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.
use AppCenter.start(...) on one Activity and then go to another Activity
Loop trying to install

### **Details**

Release is mandatory, ignoring any postpone action.
Latest release is more recent.
Calling listener.onReleaseAvailable.
Calling listener.onReleaseAvailable.
Already checking or checked latest release.
Distribute service has already been enabled.
Schedule download...
Start downloading new release, url=https:xxxx
Check download id=196
currentSize=0 totalSize=-1
Check download id=196
currentSize=72745 totalSize=10690258
Check download id=196
currentSize=72745 totalSize=10690258
Check download id=196
currentSize=72745 totalSize=10690258

Check download id=196
Download was successful for id=196 uri=content://downloads/my_downloads/196
Show install UI now intentUri=file:///data/user/0/com.android.providers.downloads/cache/downloadfile.bin
Store downloaded group id=xxx release hash=xxx release id=13
Already checking or checked latest release.

Check download id=196
Download was successful for id=196 uri=content://downloads/my_downloads/196
Show install UI now intentUri=file:///data/user/0/com.android.providers.downloads/cache/downloadfile.bin
Store downloaded group id=xxx release hash=xxx release id=13
Already checking or checked latest release.

SDK version: appCenterSdkVersion = '3.2.0'

In logs everything seems fine and are basically the same just every-time I click 'Install' keeps repeating the same logs.

**Comment by MatkovIvan** [comment]
Hi @adriatikgashi 

Could you please fill missing details in the template? What SDK version do you use? Also, I guess the logs is different that in the issue from 2018, could you please share them?

**Comment by AnastasiaKubova** [comment]
Hi, @adriatikgashi ! 
Thanks for updating your comment! I tried to reproduce your issue, but it works right for me. Could you please share reproducing steps in more details. Also, have you a chance try to reproduce it on the empty project and let me know about results?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
