### ISSUE TITLE
Clarify support of side loading for public track updates

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1415]
**Is your feature request related to a problem? Please describe.**

I know this is not purely a feature request, but this was the closest. Also I would rather get a reply from the devs rather than the support team (II have reached them before).

In AppCenter Android Distribute, I understand that side-loading is not officially supported (install via adb or any other website than the App Center portal).

This is what the doc says: https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#how-do-in-app-updates-work

> When each user opens the link in their email, the application will be installed on their device. It's important that they use the email link to install - we do not support side-loading. When an application is downloaded from the link, the SDK saves important information from cookies to check for updates later, otherwise the SDK doesn’t have that key information.

Also your support team confirmed the above:

> Yes, even from the public distribution group, you need to install the app via public url. as mentioned in the docs, SDK saves important information from cookies to check for updates later, otherwise the SDK doesn’t have that key information.
So, if you side load the app it may not work properly.

I would understand why this is the case for a private track.

Now, from our usage and testing, it's actually not the case for a public app, the update of a publicly distributed app, installed via `adb` runs just fine.
Also, it's unclear why a cookie would be needed if it's public. Is it for analytics purposes back in the dashboard?

We install our app on thousands of devices, being able to do that via `adb` rather than from the browser would save us hours of work, so we are really curious about the limits of the install via `adb` for a public app.

**Describe the solution you'd like**

Could you clarify:
- What are the cookies used for in the case of a public app?
- Where can we see where they are used in the Android SDK? (we are developers too and keen to understand)?
- Can we actually install a public app via adb, so far it seems to work?
- What won't work if we install the app via `adb`?

**Comment by AnastasiaKubova** [comment]
Hi @fabiendem ! Thanks for getting in touch with us!

1. From the `App Center` of version `3.0` cookies are used for checking release updates for private groups in the `Distribute` module. For public groups cookies are not used. For the right work the `App Center` should be configured as described [here](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#use-private-distribution-group) .
2. This check is performed [here](https://github.com/microsoft/appcenter-sdk-android/blob/3e0782a6f9b98631636f4f82fe01185091e47b6d/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L914).
3. If you download the application from the portal from the public group and install it via `adb` then this will no affect on the work our SDK.

**Comment by fabiendem** [comment]
Thanks for the reply.
If side loading via `adb` a public app is going to just work fine, could you please clarify this in the docs? Because it's a game changer at scale.

**Comment by fabiendem** [comment]
Hey @ahdbilal, I see you're the new assignee.

My colleagues and me are wondering if you're planning on updating the doc wrt the support of side loading (`adb install`) for public only apps with AppCenter Distribute.
Seeing it written down in the public doc would confirm the statements in the thread, reassure us, and make things clearer for us and anyone using AppCenter Distribute.

Thank you

**Comment by ahdbilal** [comment]
@fabiendem We are still contemplating whether to change the doc or not. As was mentioned earlier, there is nothing stopping you to use adb for public only apps with AppCenter Distribute. We do intent to keep on giving the flexibility to users to use external install methods. However there are certain limitations in using external install methods such as the download count on the app center portal will not work. We also don't formally test external installs so we are little reluctant to make changes in the doc for something that is not traceable. Anyways, I do agree with you that this is a game changer for many and therefore we will keep having the discussion internally on what can be done to better support this capability (including making required change in the document).

**Comment by fabiendem** [comment]
@ahdbilal Thank you for the thorough answer and being open about this 👍 

🗒️ We have taken note of the limitations you mentioned.

I personally keep an eye on the AppCenter Android SDK release notes but let us know if you think there is a better way to keep track of such changes.

**Comment by DmitriyKirakosyan** [comment]
Since the question is resolved, I'm closing this issue.
Feel free to reopen if you have additional questions.
