### ISSUE TITLE
Use prepared statements running sql queries

### ISSUE THREAD

**Issue by dave-89** [microsoft/appcenter-sdk-android#1428]
**Is your feature request related to a problem? Please describe.**
The class https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/SQLiteUtils.java makes use of raw SQL queries

**Describe the solution you'd like**
To avoid possible SQLi, prepared statements should be used. On the plus side, most SQL engines will perform better with pre-compiled statements

**Additional context**
Step to recreate:
* Create a vanilla react-native application
* Build the app following appcenter guide for android builds

**Comment by russelarms** [comment]
Hi, @dave-89, thanks for opening the feature request!
We'll consider the use of prepared statements.

**Comment by MatkovIvan** [comment]
I just want to mention here that SQL string is built **only** with predefined data - it doesn't use any dynamic data/input/public parameters/network requests, so SQLi is not really the case here.

**Comment by AnastasiaKubova** [comment]
The fix has been released in the version [3.3.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.3.0).
