### ISSUE TITLE
No download UI when appcenter servers can't be reached

### ISSUE THREAD

**Issue by stefanoberdoerfer** [microsoft/appcenter-sdk-android#1431]
### **Description**

If the user chooses to install a non-mandatory update and the network connection is flaky (or appcenter servers do not respond) there is no UI indication visible at all - Not even the Android OS download manager notification. After some kind of timeout there sometimes is a failure notification, but it takes very long time and is hard to notice for a normal user. The user experience gets additionally worse, if its the first time installing an update and the user has to give the "unknown install source" permission. After granting the permission it appears to the user that nothing happens at all.

I would highly appreciate to be able to control the progress UI (currently only visible for mandatory updates) or the ability to register a custom listener for download state events. (Possibly related to https://github.com/microsoft/appcenter/issues/1135)

### **Repro Steps**

1. A non-mandatory update has to be available
2. cut off internet connection after showing the corresponding update dialog
3. Choose to download the update via `Distribute.notifyUpdateAction(UpdateAction.UPDATE);`
4. Nothing happens

### **Details**

1. Which SDK version are you using?
   - Distribute Version 3.2.0
2. Which OS version did you experience the issue on?
   - Android 8.1.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
   - physical device

**Comment by AnastasiaKubova** [comment]
Hi! The feature [has been released](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.4.1), so I'm going to close this issue. Feel free to reopen it if you will have additional questions.
