### ISSUE TITLE
Allow local testing - creating a build and new release every time is very painful

### ISSUE THREAD

**Issue by caltseng** [microsoft/appcenter-sdk-android#1434]
The recommended approach (link: https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android) is very, very painful for testing if in-app updates are working properly. Developers should be able to test and validate changes locally. 

Every code change requires at least 30-45 minutes to test. 

1. Make code changes. 
2. Create an APK for this
3. Upload to AppCenter (AppCenter uploads are slow, can take 5-10 minutes for 80 MB upload)
4. Download this new build on device
5. Upload ANOTHER build with a higher version onto AppCenter to trigger in-app update. (Another 5 - 10 minutes)
6. Validate that it works properly. If not, repeat all steps.

**Comment by iamclement** [comment]
Hi @caltseng, the upload slowness seems to be a separate issue here would you be able to contact us through the [App Center portal](https://appcenter.ms) (help menu in the upper right corner: ? > Contact support) so it can be triaged separately? Thanks.

**Comment by DmitriyKirakosyan** [comment]
Hi @caltseng , you can now test in-app updates without releasing a new version each time, following these steps:
-  [Enable in-app updates for debug builds](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#enable-in-app-updates-for-debug-builds).
- Set a lower version of the application in your gradle file.
- Make sure you have at least one release on the App Center Portal with version higher than in the gradle file.

I'm closing this issue but feel free to reopen if you have additional questions.
