### ISSUE TITLE
SDK crashed while saving logs on android

### ISSUE THREAD

**Issue by histone** [microsoft/appcenter-sdk-android#1442]
### **Description**
SDK crashed while saving logs on android

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Reported on app center with live client
2. no steps

### **Details**

1. Which SDK version are you using?
    3.2.2
2. Which OS version did you experience the issue on?
    Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
   Galaxy Tab A (2017) device
4. What third party libraries are you using?
    too many libs are included.
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
com.microsoft.appcenter.crashes.Crashes.saveUncaughtException
android.os.RemoteException: Remote stack trace: at com.android.server.am.ActivityManagerService.isTopOfTask(ActivityManagerService.java:18571) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2003) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4233) at android.os.Binder.execTransact(Binder.java:739)

**Comment by annakocheshkova** [comment]
Hi there! This exception does not seem to be related to our SDK. 
Don't be confused by the `saveUncaughtException` appearing in the logs - it's there just because this method collects the stacktrace and it's part of the hierarchy because it's where the exception is caught.

**Comment by histone** [comment]
> Hi there! This exception does not seem to be related to our SDK.
> Don't be confused by the `saveUncaughtException` appearing in the logs - it's there just because this method collects the stacktrace and it's part of the hierarchy because it's where the exception is caught.

But in appcenter console  we don't have any log trace, Can you help me?

**Comment by annakocheshkova** [comment]
@histone do you mean **Log flow** tab? Do you see any other events there?

**Comment by histone** [comment]
> @histone do you mean **Log flow** tab? Do you see any other events there?

@annakocheshkova No i didn't found any other event

**Comment by annakocheshkova** [comment]
@histone have you followed the instructions on [this page](https://docs.microsoft.com/en-us/appcenter/analytics/log-flow)?

**Comment by annakocheshkova** [comment]
Hi @histone any luck? I'm closing this ticket, but feel free to re-open it in case any questions appear.
