### ISSUE TITLE
appcenter-distribute-play is not properly published or documentation incomplete

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1453]
### **Description**

The [3.3.0 update](https://github.com/microsoft/appcenter-sdk-android/blob/develop/CHANGELOG.md#app-center-distribute-play) added the `appcenter-distribute-play` library.

I have tried to setup this dependency in my project, but no matter the setup, the dependency cannot be found by Gradle at build time.

**Some details:**

It looks like it's published on Bintray:  
https://bintray.com/vsappcenter/appcenter/appcenter-distribute-play/
But not linked to JCenter:  
https://bintray.com/bintray/jcenter?filterByPkgName=appcenter-distribute-play
At https://bintray.com/vsappcenter/appcenter/appcenter-distribute-play/ you can see at the bottom right that the Linked to section is empty.

Meanwhile the `appcenter-distribute` dependency is published on Bintray:  
https://bintray.com/vsappcenter/appcenter/appcenter-distribute/
And linked to JCenter:  
https://bintray.com/bintray/jcenter?filterByPkgName=appcenter-distribute
At https://bintray.com/vsappcenter/appcenter/appcenter-distribute/ you can see at the bottom right that the Linked to section refers to the JCenter repo.

In my `build.gradle` file I have:
```
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { 
            url 'https://www.jitpack.io' 
        }
    }
}
```

And I don't know what to add to pull the new `appcenter-distribute-play` dependency.

➡️ Could you please either fix the publication or provide instructions to be able to pull this dependency?

Thank you

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new Android project, default repositories will be:
```
allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
2. Add the dependency `implementation 'com.microsoft.appcenter:appcenter-distribute:3.3.0'`, the Gradle sync will run correctly, it will build correctly
3. Replace the dependency with `implementation 'com.microsoft.appcenter:appcenter-distribute-play:3.3.0'`, the Gradle Sync will fail

### **Details**

1. Which SDK version are you using?
    - 3.3.0
2. Which OS version did you experience the issue on?
    - N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
4. What third party libraries are you using?
    - N/A
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
	- N/A

**Comment by MatkovIvan** [comment]
Hi @fabiendem 👋 

Thanks for getting in touch! We're working on fix linking to `jcenter` for this package.
You can use it via 
```groovy
maven {
    url "https://dl.bintray.com/vsappcenter/appcenter"
}
```
for now.

**Comment by fabiendem** [comment]
OK thank you, that seems to work 👍

**Comment by MatkovIvan** [comment]
Fixed
