### ISSUE TITLE
Missing country API that is available to Apple & DotNet

### ISSUE THREAD

**Issue by keith30xi** [microsoft/appcenter-sdk-android#1456]
### **Description**

Devices without SIM cards do not report their country to AppCenter. The Apple & DotNet SDKs allow for the setting of the country code.  I cannot find a similar API within the Android SDK.

https://github.com/microsoft/appcenter-sdk-apple/issues/190

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
    - 3.3.0
2. Which OS version did you experience the issue on?
    - All versions
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Emulator and Honeywell 5051
4. What third party libraries are you using?
    - NA
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here: NA

**Comment by MatkovIvan** [comment]
Hi @keith30xi,

Thanks for getting in touch!
Yep, it's not exposed to public on Android. I've converted this to a feature request.

**Comment by AnastasiaKubova** [comment]
Hi there! The feature has been released in the [4.4.2](https://github.com/microsoft/appcenter-sdk-android/releases).
