### ISSUE TITLE
Cleaning up crash related files when the device does not have net connectivity

### ISSUE THREAD

**Issue by ShreyaA** [microsoft/appcenter-sdk-android#1485]
Feature request:

There should be a mechanism to prevent the crash files from stocking up on a user's device. We have been told that this won't happen if the device cannot connect to the internet.
In our particular case for our Android apps, we have decided to retain files until the user connects to WiFi, since we do not want them to incur mobile data charges for our sake. However, if they never connect to WiFi, these files will be retained on their device.

A solution we would like:

We would like to retain some N newest crash reports on the device (similar to Hockey, N was 100 in Hockey). The older ones should be cleaned up in the background.
We can sort the crash files by lastModifiedTime and extract the report ids. Then delete all files that contain the report id in their name (in both error/ and error/minidump/ directory).

**Comment by olmisa** [comment]
Hello @ShreyaA ,
thanks for using App Center. If we delete crash data then it would be possible that some important data could be deleted.
We have a 'maxStorageSize' value which could be set before the App Center start. Could the method 'setMaxtorageSize' be applicable to your goals?
Thanks

**Comment by AnastasiaKubova** [comment]
We already have the same API (`setMaxStorageSize`) in our SDK. You can see more about it [here](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#storage-size).
I’m closing this issue but feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Comment by ShreyaA** [comment]
Hi @AnastasiaKubova ,
I had a correspondence with a member of the team and here's the answer to my queries:

1. To clarify my understanding - given that the storage setting is set to default (DB size =10MB), if my device never connects to the internet, the crash files will not be deleted - no matter how many of them reside on my device?

Yeah, it turned out to be a bug in our android SDK and I hope we'll fix it soon.
If a device never connects to the network and crashes a lot of times, the DB will be full and the newer crash logs would overwrite the oldest, throwable files should be removed when the corresponding log is overwritten. That's how it should work.

2. Also, we have generated some custom files with the same report id as the .throwable file (<report-id>.logs, <report-id>.desc) by overloading the custom exception handler. When clean up occurs, will these be deleted as well?

I haven't looked at this thoroughly yet, I expect they won't be cleaned up because the SDK removes files filtered by their extension. 

In light of these responses, I have commenced making changes in our app code to clean up crash related files if they exceed a certain number (100-150). Will this adversely impact AppCenter's functioning?

**Comment by AnastasiaKubova** [comment]
Regarding the bug from the first point, we already prepared a fix for it.  We will notify you when the fix will be released.

Regarding your question. This can affect the SDK in the case when you remove throwable files before logs are sending to the portal. In this case the data about stack trace can be lost when calling [this](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#should-the-crash-be-processed) function for example. But I think it should not affect the crash report on the portal.

**Comment by ShreyaA** [comment]
Any timeline on the release of the fix? Few weeks? In any case, I suppose I will have to take responsibility for my custom crash files that are captured at the time of the crash. I am contemplating whether to only tend to our custom files for now, instead of all crash related files (including .throwable, .json etc.)

I was intending on doing the clean up before shouldProcess returns a value. In the code, it does check whether the file contents are null or not. So I did not observe any adverse effects in the short term.

**Comment by AnastasiaKubova** [comment]
We already prepared a fix for it and I hope that it will be released in December or January release. We will notify you when the fix will be released.

**Comment by ShreyaA** [comment]
Thank you.
Could you also please consider my feature request that incorporates cleaning up of programmer generated custom crash files? If required, we'll put them in a specific directory. 
Also, what is the deletion/clean up criteria that will be followed? On https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#storage-size it says, "The logs older than 25 days will be discarded."

**Comment by AnastasiaKubova** [comment]
> Could you also please consider my feature request that incorporates cleaning up of programmer generated custom crash files? If required, we'll put them in a specific directory.

Could you please explain why `setMaxStorageSize` API does not fit for you?

>Also, what is the deletion/clean up criteria that will be followed? On https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#storage-size it says, "The logs older than 25 days will be discarded."

Let me clarify with the team about it.

**Comment by ShreyaA** [comment]
I was under the impression that the DB only accounts for .throwable and .json files? I am not clear on how the DB is leveraged. Do we store the reports in it? How do I also store my custom files in that DB?

Thank you.

**Comment by AnastasiaKubova** [comment]
After start the app our SDK check `.json` files and save data from it to the database and remove `.json` files after. In the fix, which I mention above will not use `.throwable` files.
But our database is used not only for the Crashes module. It is also used for saving data from the Analytics module.

Could you please clarify which data and files you are going to store in the database?

**Comment by ShreyaA** [comment]
The files we would store would be 1) logcat logs, and 2) a file that has metadata containing like information about the device, the process ID etc.

These are our custom error attachments actually.

**Comment by AnastasiaKubova** [comment]
I am not sure that it is right behavior to save custom data to the database of SDK.
If you need to save data for attachments you can save it to your own database and get data from it in the `getErrorAttachments` [callback](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#add-attachments-to-a-crash-report) for example. If you going to save custom data to the database of SDK you should take care about cleaning custom data yourselves.
Your custom files you can clean in the `onSendingSucceeded` [callback](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#the-following-callback-will-be-invoked-before-the-sdk-sends-a-crash-log).

**Comment by ShreyaA** [comment]
Yes, it does seem questionable.
We are currently doing what you mentioned. But without internet connectivity, the files just sit on the device if they cannot be sent. It would be ideal if AppCenter would clean up all old crash files, say older than 25 days.
If this cannot include custom files that have the same report id as AppCenter crash reports, we will have to take care of it ourselves. For this purpose, we would like to follow the same criteria as AppCenter.

Another question, what happens to minidump files? I cannot locate them on the device.

**Comment by AnastasiaKubova** [comment]
The minidump files located in `error -> minidump -> pending` folder. 
Before sending the data from minidump files are saved to the database and after that files are removed.

**Comment by AnastasiaKubova** [comment]
The fix has been released in version `4.1.0`. Please update the App Center SDK to the [latest version](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.1.0) and let me know if this issue still persists.
