### ISSUE TITLE
Make AppCenter to start new user's session programmatically

### ISSUE THREAD

**Issue by dzhukovski** [microsoft/appcenter-sdk-android#1495]
It would be great to get a possibility to trigger new user's session programmatically. 

**It may look like this:**

**AppCenter**.StartSession();
**AppCenter**.EndSession();
or
**Analytics**. StartSession();
**Analytics**. EndSession();

**An extra info:**
In our android mobile solution we have a background service which provides bunch of public end points for other applications. The service is running all the time and as a result it has one long session (we don't control it). In our case its not convenient way of usage because it generates long unreadable user flows in Application Insights. It would be really great to get an opportunity to manage the user sessions manually. Ideally each public endpoint reuqest should trigger a new session.

**Comment by DmitriyKirakosyan** [comment]
hi @dzhukovski,

Thank you for getting in touch with us and for your feature request!

Unfortunately, our SDK has no focus on background services like yours.
I'll keep this issue open to see if there are others who want this feature as well.

Thanks.

**Comment by AnastasiaKubova** [comment]
Hi there! The feature [has been released](https://github.com/microsoft/appcenter-sdk-android/releases).
