### ISSUE TITLE
In-app update - Failed to download app update

### ISSUE THREAD

**Issue by donEgro** [microsoft/appcenter-sdk-android#1499]
Hi, we are experiencing the same problem as described in ticket #1418 - we've set an old version to mandatory to force update of some obsolete versions, but the whole distribution stopped working. Doesn't matter if installed version is older or newer than the mandatory one, every update fails on 'Failed to download app update'.

I've tried to upload new builds, or install older ones before update, but the update still fails. Could you help us, please?

- SDK version 3.3.1
- App permissions checked and confirmed
- Distribution group - public
- Android 9

> 2021-01-14 10:32:04.867 7634-7758/? D/AppCenterDistribute: Start download 4.37-cz (437) update.
2021-01-14 10:32:06.912 7634-7770/? D/AppCenterDistribute: Check download id=30
2021-01-14 10:32:06.920 7634-7771/? D/AppCenterDistribute: Download was successful for id=30
2021-01-14 10:32:06.922 7634-7771/? D/AppCenterDistribute: Cannot resolve install intent for content://downloads/all_downloads/30
2021-01-14 10:32:06.922 7634-7771/? E/AppCenterDistribute: Failed to download 4.37-cz (437) update: Installer not found

**Comment by russelarms** [comment]
Hi there, we'll look into this soon and get back to you.

**Comment by russelarms** [comment]
@donEgro I've tried the in-app updates flow, it worked smoothly for me:

1. Uploaded two builds through the portal. 
2. Updated from 1st to 2nd. 
3. Removed the app. 
4. Made 2nd release mandatory on the portal. 
5. Downloaded 1st release, updated to 2nd successfully.

Could please describe in detail how you came to this problem? How you uploaded your releases (portal, cli, distributed after AC Build)? 
As I understood if you upload two newer versions an update from the first one to the second would also fail?

**Comment by donEgro** [comment]
@russelarms Hi, after further investigation I've found the cause of this issue.

We use Bitrise CI/CD for application build & deployment, and its [steps-appcenter-deploy-android](https://github.com/bitrise-steplib/steps-appcenter-deploy-android) plugin to deploy built apks into appcenter. After upgrading this plugin from version 1.1.0 to 2.0.2, the problem described in this ticket occured. The APK was uploaded successfuly, everything looks ok, but when I tried to install new version the problem described in this ticket appeared. Downgrade to version 1.1.0 of this plugin fixed this issue. 
I've looked into source codes of this plugin, but I can't tell what exactly in 2.0.2 could cause this behavior. 

Is it possible that using this version causes some kind of data inconsistency in appcenter? Version 1.1.0 works fine, same as the manual upload over web. Version 2.0.2 successfuly uploads apk, everything looks normal, but the installation on device fails.

Thank you

**Comment by russelarms** [comment]
> Is it possible that using this version causes some kind of data inconsistency in appcenter? Version 1.1.0 works fine, same as the manual upload over web. Version 2.0.2 successfuly uploads apk, everything looks normal, but the installation on device fails.

@donEgro It seems to be the case, I'd suggest contacting plugin maintainers so they can fix it.
I'm closing this issue right now as it is not SDK related.
