### ISSUE TITLE
Login for In-App-Updates cannot be canceled for private track

### ISSUE THREAD

**Issue by CordulaAndune** [microsoft/appcenter-sdk-android#1504]
After updating App Center SDK from version 2.5.1 to 4.1.0 the automated test are blocked by the app center login. Before it was possible to cancel the login via back press and proceed with the automated tests. With the new version the login cannot be cancelled anymore since the website is loaded again after back press.

AppCenter is initialized with:

```AppCenter.setLogLevel(Log.VERBOSE)
Distribute.setEnabledForDebuggableBuild(true)
Distribute.setUpdateTrack(UpdateTrack.PRIVATE)
AppCenter.start(
    application,
    appCenterApiToken,
    Distribute::class.java,
    Crashes::class.java
) 
```

### **Repro Steps**

1. Use AppCenter with Private track and add Distribute in the app
2. Open the app
3. Browser opens to login to app center
4. Tap back

### **Details**

1. Which SDK version are you using?
    - 4.1.0
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

> 2021-02-09 15:29:45.547 19985-19985/ D/AppCenterDistribute: Resume distribute workflow...2021-02-09 15:29:45.551 19985-19985/ D/AppCenterDistribute: No token, need to open browser to url=https://install.appcenter.ms/apps/xxx
> 2021-02-09 15:29:45.560 19985-19985/ D/AppCenterDistribute: Default browser seems to be android/com.android.internal.app.ResolverActivity
> 2021-02-09 15:29:45.560 19985-19985/ D/AppCenterDistribute: Default browser is actually a picker...
> 2021-02-09 15:29:45.561 19985-19985/ D/AppCenterDistribute: Picking first browser in list.
> 2021-02-09 15:29:45.561 19985-19985/ D/AppCenterDistribute: Launch browser=com.android.chrome/com.google.android.apps.chrome.IntentDispatcher
> 2021-02-09 15:29:45.865 19985-19985/ D/AppCenterCrashes: The memory running level (20) was saved.
> 2021-02-09 15:29:46.068 19985-19985/ D/AppCenterCrashes: The memory running level (80) was saved.

Is there any possibility to cancel the login to use the app provided via AppCenter for the automated tests?

**Comment by carstenhag** [comment]
(I'm a colleague of Cordula 😄 ). We aware of the note at https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android that says
> If you're running automated UI tests, enabled in-app updates will block your automated UI tests as they'll try to authenticate against the App Center backend. We recommend to not enable App Center Distribute for your UI tests.

but this issue is also annoying for our testers/business colleagues, because they always have to log in before accessing the app. On 2.5.1 they authenticated once at the appcenter.ms page or the app, then downloaded the app. If they wanted to update, they either logged in or were already logged in and were prompted to log in.

So as far as I understand we want to stay on the Public track, but still want to show the in-app-update. I tried this at first, with AppCenter 4.1.0:

```kotlin
                AppCenter.setLogLevel(Log.VERBOSE)
                Distribute.setEnabledForDebuggableBuild(true)
                AppCenter.start(
                    application,
                    appCenterApiToken,
                    Distribute::class.java,
                    Crashes::class.java
                )
                Distribute.checkForUpdate()
```
but with that nothing AppCenter-related showed up or any browser launched.

**Comment by russelarms** [comment]
Hi @CordulaAndune @carstenhag , thanks for reaching out!
Regarding the first question, it's unlikely to be changed in the near future. I think switching to public groups should help for your tests to run.
Regarding the second question:
Normally you need to authenticate through appcenter.ms once and after that Private groups should work without logging in.

>So as far as I understand we want to stay on the Public track, but still want to show the in-app-update. I tried this at first, with AppCenter 4.1.0:
>but with that nothing AppCenter-related showed up or any browser launched.

That's strange. If there's an available update in a public group, you should see an update dialog. Could you please share logs filtered by `AppCenterDistribute` for this case?

**Comment by CordulaAndune** [comment]
Hi @russelarms, 
thank you for your quick response!
Here are the logs you requested: 

> 2021-02-10 15:08:42.728 16274-16414/g D/AppCenterDistribute: Distribute workflow will be resumed on activity resume event.
> 2021-02-10 15:08:42.728 16274-16274/g D/AppCenterDistribute: Resume distribute workflow...
> 2021-02-10 15:08:42.729 16274-16274/g D/AppCenterDistribute: InstallerPackageName=com.google.android.packageinstaller
> 2021-02-10 15:08:42.730 16274-16274/g D/AppCenterDistribute: Get latest release details...
> 2021-02-10 15:08:42.731 16274-16274/g D/AppCenterDistribute: Check if we need to report release installation..
> 2021-02-10 15:08:42.731 16274-16274/g D/AppCenterDistribute: Current release was already reported, skip reporting.
> 2021-02-10 15:08:42.756 16274-16414/g I/AppCenterDistribute: A check for update is already ongoing.
> 2021-02-10 15:08:43.107 16274-16274/g D/AppCenterDistribute: Resume distribute workflow...
> 2021-02-10 15:08:44.425 16274-16274/g D/AppCenterDistribute: No sessions were logged before, ignore sending of the distribution start session log.
> 2021-02-10 15:08:44.425 16274-16274/g D/AppCenterDistribute: Check if latest release is more recent.
> 2021-02-10 15:08:44.425 16274-16274/g D/AppCenterDistribute: Latest release more recent=false

The app was installed via the AppCenter-App and also there were newer versions available. No dialog opened after entering the app.

**Comment by russelarms** [comment]
> 2021-02-10 15:08:44.425 16274-16274/g D/AppCenterDistribute: Latest release more recent=false

Probably the apk's version code doesn't pass this check:
https://github.com/microsoft/appcenter-sdk-android/blob/658788bd9305f9b3f6bb0d5e3891d5248e24e527/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L1380-L1390

**Comment by Jamminroot** [comment]
We haven't heard from you for a while, @CordulaAndune, does the issue still persist for you? Need you any further assistance, please come back and reopen the ticket, as I'm going to close it now.

**Comment by carstenhag** [comment]
We have found out though why the `isMoreRecent` checked failed. We either had no distribution group at all or a really old one that was not in use, with releases from 2019.

So it seems like it is now needed to do one of the following:

* Create a Public distribution group, make sure the pipeline releases the versions there as well
* Keep only having "Collaborators" aka no distribution group, set track to private, have to log in (be it as a user or an automates test)
* Disable In-App-Updates for everybody, manually install releases via appcenter.ms or app
* Disable In-App-Updates for automated tests only

Is there a difference between the old behavior (no distribution group, only collaboratos, only have to log in to download update optionally) and the 1st point? If so, that would be the only viable option for us I think. Thanks in advance :)

**Comment by Jamminroot** [comment]
Hey @carstenhag, Collaborators is default public distribution group, which contains all users in your organization; Having public distribution group generally makes no difference in the update distribution scenario.

**Comment by carstenhag** [comment]
Ah I see, thanks. So keeping the UpdateTrack at PUBLIC it should not force logins with 4.1.0, right? Will perhaps try out the next days.

**Comment by Jamminroot** [comment]
Yeah, that's the expected behavior - having public update track should not force login prompts.
