### ISSUE TITLE
Using Appcenter with Android Work Manager Workers

### ISSUE THREAD

**Issue by cacodev** [microsoft/appcenter-sdk-android#1512]
I can not find a way to get appcenter to work with tasks running via android's work manager api (https://developer.android.com/reference/androidx/work/WorkManager#:~:text=Public%20methods%20%20%20%20abstract%20WorkContinuation%20,Gets%20a%20...%20%2022%20more%20rows).  Seems that any way of starting appcenter requires an application object which jobs running via work manager don't have.

It would be handy to have a way of reporting analytics and crashes to appcenter when running in a work manager worker context.

My use case is that I have a whole fleet of android devices in my organization and we've started using background tasks for collecting device health without the user having to do anything. I would like to see in appcenter when the daily task runs and leverage app center for crash reporting. Would be helpful to also track custom events for logging analytics from the background.

**Comment by Jamminroot** [comment]
Hey, @cacodev, thanks for reaching out.

There shouldn't really be any issues working with WorkerManagers. Here's a sample implementation I used to verify SDK is working with workers
TestWorker class:
```java
public static class TestWorker extends Worker {
    public TestWorker(
            @NonNull Context context,
            @NonNull WorkerParameters params) {
        super(context, params);
    }

    @NonNull
    @Override
    public Result doWork() {
        Log.d(LOG_TAG, "Tracking event");
        Analytics.trackEvent("This is an event tracked in a worker");
        return Result.success();
    }
}
```
Setting the worker up:
```java
WorkRequest workRequest = new OneTimeWorkRequest.Builder(TestWorker.class).build();
WorkManager.getInstance().enqueue(workRequest);
```

![image](https://user-images.githubusercontent.com/6387654/110802335-8819d900-8297-11eb-947e-b3865afd4639.png)

Can you check if code is working? If it is not working - can you share verbose logs?

**Comment by cacodev** [comment]
Looks like this all works as expected. Thank you for clarifying.  Additionally, it works in ContentProviders as well:

`override fun query(
        uri: Uri, projection: Array<String>?, selection: String?,
        selectionArgs: Array<String>?, sortOrder: String?
    ): Cursor? {
        Analytics.trackEvent("ContentProviderQuery")
...
}`

Which is handy in my environment cause I can ask the consumers of my content provider to include a id query string to log for analytics reasons.  Just made my day :)

**Comment by Jamminroot** [comment]
Glad its resolved :) Have a nice day!
