### ISSUE TITLE
Security Issue Alert - Using Known Vulnerable Cryptography Encryption Algorithm

### ISSUE THREAD

**Issue by tunguyenngoc** [microsoft/appcenter-sdk-android#1521]
### **Description**
Dear Microsoft Team,

We got an security issue reported below while using the library.

It is observed that the lib is using ‘AES/CBC/PKCS7Padding’ which is a broken or risky cryptography algorithm.

![PKCS7Padding](https://user-images.githubusercontent.com/43739603/112783171-e48f3d80-9078-11eb-9d84-8fee8b6f5dcb.JPG)

This specific mode of CBC with PKCS7Padding is susceptible to padding oracle attacks. An adversary could potentially decrypt the message if the system exposed the difference between plaintext with invalid padding or valid padding. The distinction between valid and invalid padding is usually revealed through distinct error messages being returned for each condition.

Could you please help to confirm if the issue reported is not a problem, the lib has been tested and safe to use?

Sincerely,
Jackie Nguyen

**Comment by DmitriyKirakosyan** [comment]
hi @tunguyenngoc 

Thank you for reporting a potential security issue!
We will discuss it within the team and I will get back to you with an update.

**Comment by DmitriyKirakosyan** [comment]
Hi @tunguyenngoc

We are using this encryption algorithm to store App Center SDK data locally on the device. We are not sending the encrypted data over the network. Also, we do not expose the error details (eg. whether it was incorrect padding or incorrect message).
Considering all above, I'm confirming that the SDK is not vulnerable to the "Padding oracle attack".

However, we will consider improving this part of code to avoid such alerts in future.

Closing the issue.
Please let me know if you still have concerns.

**Comment by tunguyenngoc** [comment]
Thanks @DmitriyKirakosyan and the team for the clarification and confirmation. God bless you!
Bro,
Jackie
