### ISSUE TITLE
[Question] [Xamarin.Forms] Android 4.4 crash on AppCenter.Start()

### ISSUE THREAD

**Issue by JTOne123** [microsoft/appcenter-sdk-android#1524]
### **Description**

In my Xamarin.Forms app at the moment of initialization; when code goes to the line " AppCenter.Start(AppCenterSecret, typeof(Analytics), typeof(Crashes)); ", it immediately crashes each time when it started on Android 4.4 (other android versions work well)

Can I use AppCenter v4.2.0 with android 4.4?

### **Details**
1. Which SDK version are you using?
    - 4.2.0
2. Which OS version did you experience the issue on?
    - Android 4.4
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Emulator
4. Xamarin Forms Version
   - 5
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

04-01 18:16:57.044 D/Mono    (12391): Requesting loading reference 38 (of 41) of WApp.dll
04-01 18:16:57.044 D/Mono    (12391): Loading reference 38 of WApp.dll asmctx DEFAULT, looking for Microsoft.Extensions.Configuration.Binder, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
04-01 18:16:57.044 D/Mono    (12391): Assembly Ref addref WApp[0xb87eee30] -> Microsoft.Extensions.Configuration.Binder[0xb87afdb0]: 3
04-01 18:16:57.124 D/Mono    (12391): Requesting loading reference 3 (of 4) of Microsoft.AppCenter.dll
04-01 18:16:57.124 D/Mono    (12391): Loading reference 3 of Microsoft.AppCenter.dll asmctx DEFAULT, looking for Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
04-01 18:16:57.124 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter[0xb87acfe0] -> Mono.Android[0xb894e2c0]: 80
04-01 18:16:57.194 D/Mono    (12391): DllImport searching in: '__Internal' ('(null)').
04-01 18:16:57.194 D/Mono    (12391): Searching for 'java_interop_jnienv_call_void_method_a'.
04-01 18:16:57.194 D/Mono    (12391): Probing 'java_interop_jnienv_call_void_method_a'.
04-01 18:16:57.194 D/Mono    (12391): Found as 'java_interop_jnienv_call_void_method_a'.
04-01 18:16:57.194 D/Mono    (12391): Requesting loading reference 4 (of 5) of Microsoft.AppCenter.Analytics.dll
04-01 18:16:57.194 D/Mono    (12391): Loading reference 4 of Microsoft.AppCenter.Analytics.dll asmctx DEFAULT, looking for Microsoft.AppCenter.Analytics.Android.Bindings, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8a600e2fee7ba272
04-01 18:16:57.194 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter.Analytics[0xb87a93c0] -> Microsoft.AppCenter.Analytics.Android.Bindings[0xb87a84f0]: 2
04-01 18:16:57.194 D/Mono    (12391): Requesting loading reference 3 (of 4) of Microsoft.AppCenter.Analytics.Android.Bindings.dll
04-01 18:16:57.194 D/Mono    (12391): Loading reference 3 of Microsoft.AppCenter.Analytics.Android.Bindings.dll asmctx DEFAULT, looking for Microsoft.AppCenter.Android.Bindings, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8a600e2fee7ba272
04-01 18:16:57.194 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter.Analytics.Android.Bindings[0xb87a84f0] -> Microsoft.AppCenter.Android.Bindings[0xb87aa2e0]: 4
04-01 18:16:57.194 D/Mono    (12391): Requesting loading reference 2 (of 4) of Microsoft.AppCenter.Analytics.Android.Bindings.dll
04-01 18:16:57.194 D/Mono    (12391): Loading reference 2 of Microsoft.AppCenter.Analytics.Android.Bindings.dll asmctx DEFAULT, looking for Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
04-01 18:16:57.194 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter.Analytics.Android.Bindings[0xb87a84f0] -> Java.Interop[0xb89740d0]: 19
04-01 18:16:57.194 D/Mono    (12391): Requesting loading reference 2 (of 4) of Microsoft.AppCenter.Crashes.Android.Bindings.dll
04-01 18:16:57.194 D/Mono    (12391): Loading reference 2 of Microsoft.AppCenter.Crashes.Android.Bindings.dll asmctx DEFAULT, looking for Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
04-01 18:16:57.194 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter.Crashes.Android.Bindings[0xb87ab230] -> Java.Interop[0xb89740d0]: 20
04-01 18:16:57.194 D/Mono    (12391): Requesting loading reference 4 (of 6) of Microsoft.AppCenter.Crashes.dll
04-01 18:16:57.194 D/Mono    (12391): Loading reference 4 of Microsoft.AppCenter.Crashes.dll asmctx DEFAULT, looking for Microsoft.AppCenter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8a600e2fee7ba272
04-01 18:16:57.194 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter.Crashes[0xb87ac100] -> Microsoft.AppCenter[0xb87acfe0]: 4
04-01 18:16:57.194 D/Mono    (12391): Requesting loading reference 2 (of 6) of Microsoft.AppCenter.Crashes.dll
04-01 18:16:57.194 D/Mono    (12391): Loading reference 2 of Microsoft.AppCenter.Crashes.dll asmctx DEFAULT, looking for Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
04-01 18:16:57.194 D/Mono    (12391): Assembly Ref addref Microsoft.AppCenter.Crashes[0xb87ac100] -> Mono.Android[0xb894e2c0]: 81
04-01 18:16:57.194 I/AppCenterCrashes(12391): Set up Xamarin crash handlers.
04-01 18:16:57.214 D/Mono    (12391): DllImport searching in: '__Internal' ('(null)').
04-01 18:16:57.214 D/Mono    (12391): Searching for 'java_interop_jnienv_new_object_array'.
04-01 18:16:57.214 D/Mono    (12391): Probing 'java_interop_jnienv_new_object_array'.
04-01 18:16:57.214 D/Mono    (12391): Found as 'java_interop_jnienv_new_object_array'.
04-01 18:16:57.224 D/Mono    (12391): DllImport searching in: '__Internal' ('(null)').
04-01 18:16:57.224 D/Mono    (12391): Searching for 'java_interop_jnienv_set_object_array_element'.
04-01 18:16:57.224 D/Mono    (12391): Probing 'java_interop_jnienv_set_object_array_element'.
04-01 18:16:57.224 D/Mono    (12391): Found as 'java_interop_jnienv_set_object_array_element'.
04-01 18:16:57.224 I/AppCenter(12391): App Center SDK configured successfully.
04-01 18:16:57.224 D/AppCenter(12391): Cannot read instrumentation variables in a non-test environment.
04-01 18:16:57.224 D/AppCenter(12391): Cannot read instrumentation variables in a non-test environment.
04-01 18:16:57.234 D/AppCenter(12391): Loaded stored sessions: {1617283251027=1617283251027//1617283251025, 1617284180473=1617284180473//1617284180471, 1617284764915=1617284764915//1617284764913, 1617284848677=1617284848677//1617284848674, 1617285606517=1617285606517//1617285606514, 1617285727219=1617285727219//1617285727215, 1617287542110=1617287542110//1617287542107, 1617287727081=1617287727081//1617287727076, 1617288307991=1617288307991//1617288307988, 1617289931159=1617289931159//1617289931156}
04-01 18:16:57.234 D/Mono    (12391): DllImport searching in: '__Internal' ('(null)').
04-01 18:16:57.234 D/Mono    (12391): Searching for 'java_interop_jnienv_get_object_array_element'.
04-01 18:16:57.234 D/Mono    (12391): Probing 'java_interop_jnienv_get_object_array_element'.
04-01 18:16:57.234 D/Mono    (12391): Found as 'java_interop_jnienv_get_object_array_element'.
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to find class referenced in signature (Landroid/net/Network;)
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to find class referenced in signature (Landroid/net/Network;)
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to find class referenced in signature (Landroid/net/Network;)
In mgmain JNI_OnLoad04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to find class referenced in signature (Landroid/net/Network;)

04-01 18:16:57.234 I/dalvikvm(12391): Could not find method android.net.ConnectivityManager.getAllNetworks, referenced from method com.microsoft.appcenter.utils.NetworkStateHelper.isAnyNetworkConnected
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to resolve virtual method 1876: Landroid/net/ConnectivityManager;.getAllNetworks ()[Landroid/net/Network;
04-01 18:16:57.234 D/dalvikvm(12391): VFY: replacing opcode 0x6e at 0x0002
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to find class referenced in signature (Landroid/net/Network;)
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to find class referenced in signature (Landroid/net/Network;)
04-01 18:16:57.234 I/dalvikvm(12391): Could not find method android.net.ConnectivityManager.getAllNetworks, referenced from method com.microsoft.appcenter.utils.NetworkStateHelper.onNetworkLost
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to resolve virtual method 1876: Landroid/net/ConnectivityManager;.getAllNetworks ()[Landroid/net/Network;
04-01 18:16:57.234 D/dalvikvm(12391): VFY: replacing opcode 0x6e at 0x001d
04-01 18:16:57.234 I/dalvikvm(12391): Could not find method android.net.ConnectivityManager.unregisterNetworkCallback, referenced from method com.microsoft.appcenter.utils.NetworkStateHelper.close
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to resolve virtual method 1882: Landroid/net/ConnectivityManager;.unregisterNetworkCallback (Landroid/net/ConnectivityManager$NetworkCallback;)V
04-01 18:16:57.234 D/dalvikvm(12391): VFY: replacing opcode 0x6e at 0x000a
04-01 18:16:57.234 E/dalvikvm(12391): Could not find class 'android.net.NetworkRequest$Builder', referenced from method com.microsoft.appcenter.utils.NetworkStateHelper.reopen
04-01 18:16:57.234 W/dalvikvm(12391): VFY: unable to resolve new-instance 473 (Landroid/net/NetworkRequest$Builder;) in Lcom/microsoft/appcenter/utils/NetworkStateHelper;
04-01 18:16:57.234 D/dalvikvm(12391): VFY: replacing opcode 0x22 at 0x0000
04-01 18:16:57.234 D/dalvikvm(12391): DexOpt: unable to opt direct call 0x075d at 0x02 in Lcom/microsoft/appcenter/utils/NetworkStateHelper;.reopen
04-01 18:16:57.234 W/dalvikvm(12391): Unable to resolve superclass of Lcom/microsoft/appcenter/utils/NetworkStateHelper$1; (468)
04-01 18:16:57.234 W/dalvikvm(12391): Link of class 'Lcom/microsoft/appcenter/utils/NetworkStateHelper$1;' failed
04-01 18:16:57.234 D/dalvikvm(12391): DexOpt: unable to opt direct call 0x8a15 at 0x0c in Lcom/microsoft/appcenter/utils/NetworkStateHelper;.reopen
04-01 18:16:57.234 W/dalvikvm(12391): threadid=18: thread exiting with uncaught exception (group=0xa4ce6b20)
04-01 18:16:57.234 W/        (12391): Thread 0xb9425620 may have been prematurely finalized
04-01 18:16:57.234 F/        (12391): * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/utils/mono-threads.c:650, condition `info' not met, function:mono_thread_info_current, 
04-01 18:16:57.234 F/libc    (12391): Fatal signal 6 (SIGABRT) at 0x00003067 (code=-6), thread 12415 (ppCenter.Looper)
04-01 18:16:57.274 D/Mono    (12391): Requesting loading reference 8 (of 9) of Microsoft.Extensions.Logging.Configuration.dll
04-01 18:16:57.274 D/Mono    (12391): Loading reference 8 of Microsoft.Extensions.Logging.Configuration.dll asmctx DEFAULT, looking for Microsoft.Extensions.Configuration.Binder, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
04-01 18:16:57.274 D/Mono    (12391): Assembly Ref addref Microsoft.Extensions.Logging.Configuration[0xb87bf2f0] -> Microsoft.Extensions.Configuration.Binder[0xb87afdb0]: 4
04-01 18:16:57.324 D/Mono    (12391): Requesting loading reference 4 (of 9) of Microsoft.Extensions.Logging.Configuration.dll
04-01 18:16:57.324 D/Mono    (12391): Loading reference 4 of Microsoft.Extensions.Logging.Configuration.dll asmctx DEFAULT, looking for Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
04-01 18:16:57.324 D/Mono    (12391): Assembly Ref addref Microsoft.Extensions.Logging.Configuration[0xb87bf2f0] -> Microsoft.Extensions.Logging.Abstractions[0xb87be3b0]: 7

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Since the [4.0.0](https://github.com/microsoft/appcenter-sdk-android/blob/develop/CHANGELOG.md#version-400) version of App Center SDK the [minimum Android SDK version](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin#1-prerequisites) should be 21 API level (Android 5.0) or later.
