### ISSUE TITLE
Google play sent a warning regarding using hockey SDK

### ISSUE THREAD

**Issue by ronnyremesnik** [microsoft/appcenter-sdk-android#1526]
### **Details**
We got a message lately from google play that our app is using hockey SDK
but it's already more than a year that we are not using it, we are using app center SDK 3.3.0
maybe it's using it inside?
Thanks for the help!

1. Which SDK version are you using?
    - 3.3.0
    -only the 
com.microsoft.appcenter:appcenter-analytics
and
com.microsoft.appcenter:appcenter-crashes
packages, 
we are not using the distribute package, 
I found this article : 
https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#prepare-your-google-play-build
But I didn't understand what should I do since we are not using the 
com.microsoft.appcenter:appcenter-distribute
package...

2. Which OS version did you experience the issue on?
    - 
3. What device version did you see this error on?  Were you using an emulator or a physical device?
   -
4. What third party libraries are you using?
    - 
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to 

<img width="1090" alt="Screen Shot 2021-04-07 at 11 15 17" src="https://user-images.githubusercontent.com/50165476/113836553-a6d79680-9795-11eb-8d56-50f4567691d8.png">

**Comment by MatkovIvan** [comment]
Hi @ronnyremesnik,

Thanks for getting in touch! Based on the description, it looks like false-positive detection and it is not related to our SDK. It should not be a problem without `com.microsoft.appcenter:appcenter-distribute` and an old HockeySDK in your app. However, please check if your app doesn't contain the code (or other libraries) for downloading/installing new versions or other applications. I'd suggest contacting Google for clarification. Feel free to add appcentersdk@microsoft.com in cc so our team will assist with any questions regarding App Center SDK.

Best,
Ivan

**Comment by MrMuracle** [comment]
Almost the same problem on my end. The app I'm working on had Hockey SDK 5.1.1 (removed it for now to meet the Google Play's requirements). I've got the same warning as well.

**Comment by ronnyremesnik** [comment]
@MatkovIvan @MrMuracle 
I think I found the problem, looks like we had a "retained" version in google play, the old version that still was active and this version contains the old hockey app SDK.
I'll update once we'll remove that old version.

**Comment by MrMuracle** [comment]
Hi @ronnyremesnik,

Any updates on the problem or solution?

Thanks in advance!

**Comment by MatkovIvan** [comment]
Hi @ronnyremesnik, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.

@MrMuracle - I guess my previous reply should fit your case too. If there are no HockeySDK and distribute module in your app - you should see no warnings. Please re-check active versions in Google Play console.

**Comment by crazycoder1999** [comment]
I received 2 emails for both of our apps using appcenter sdk (previously hockeyapp) about policy compliants.
We checked on play console, on "policy status" and there is no message there, no policy problem present.
In the end we will update the apps to the latest sdk (we were using 3.3.1)
I think it was a wrong automatic message from google.
