### ISSUE TITLE
Explicitly specify `android:exported` for every components containing in manifest

### ISSUE THREAD

**Issue by elliemehrganrad** [microsoft/appcenter-sdk-android#1535]
### **Description**

As one of the changes on apps targeting Android 12, it is forced to explicitly specify android:exported for every components containing `intent-filter` in manifest.

Targeting Android 12 we get manifest merge conflict caused by appcenter SDK 4.1.1

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Set the `targetSdkVersion` to "S
2. Try to rebuild

### **Details**

1. Which SDK version are you using?
    - 4.1.1
2. Which OS version did you experience the issue on?
    - Android 12
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Google Pixel 4a emulator
4. What third party libraries are you using?
    - `com.microsoft.appcenter:appcenter-analytics:4.1.1`
    - `com.microsoft.appcenter:appcenter-crashes:4.1.1`
    - `com.microsoft.appcenter:appcenter-distribute:4.1.1`
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

**Comment by russelarms** [comment]
Closing as a duplicate to https://github.com/microsoft/appcenter-sdk-android/issues/1506
