### ISSUE TITLE
Comply with Google Play Device and Network Abuse policy

### ISSUE THREAD

**Issue by elliemehrganrad** [microsoft/appcenter-sdk-android#1541]
### **Description**

Our application just got suspended from Google Play Store because of using a non-compliant version of Microsoft Appcenter SDK 2.5.0. 
We would like to make sure that the lates version of appcenter SDK fixes this issue. 

### **Details**

1. Which SDK version are you using?
    - 2.5.0

![image](https://user-images.githubusercontent.com/52495821/121172296-d408f980-c857-11eb-9fef-5f3c22f5e823.png)

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Could you please clarify for what reason your app was blocked exactly? And which modules of App Center SDK do you use in your app?

**Comment by AnastasiaKubova** [comment]
If you use Distribute module in your app please follow [this guideline](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#prepare-your-google-play-build) about preparing your app for publishing to Google Play.

**Comment by elliemehrganrad** [comment]
Hi,

The reason is about ​Device and Network Abuse policy. We use these dependancies:
"com.microsoft.appcenter:appcenter-analytics:2.5.0"
"com.microsoft.appcenter:appcenter-crashes:2.5.0"
"com.microsoft.appcenter:appcenter-distribute:2.5.0"

**Comment by AnastasiaKubova** [comment]
Looks like your issue related to Distribute module. The link from previous comment should help you to resolve this problem. 
I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by elliemehrganrad** [comment]
Yes, the goal of the ticket was to make sure that the issue has been fixed in the latest version. Thank you 👍
