### ISSUE TITLE
Check for the checksum once update download is completed - Android

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1575]
**Is your feature request related to a problem? Please describe.**

Using Android AppCenter Distribute, while the download of the update will run fine, sometimes the user may get an error at installation (system level):
```
Parse Error
There was a problem parsing the package
```

Once this is the case, I don't think there is any way for the user to recover, apart from clearing the data of the app from the settings.

**Describe the solution you'd like**
I believe this can happen if the download is corrupted (for some reasons something goes wrong during the download)
Afaik, best is to compare the md5 checksum of the file downloaded with the expected checksum (you have server side).
If they don't match, re-trigger the download rather than sending the user to the install flow.

Is that something already integrated in Appcenter Android distribute in some way.
If not would you consider adding this check?

**Comment by AnastasiaKubova** [comment]
Hi! The feature [has been released](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.4.1), so I'm going to close this issue. Feel free to reopen it if you will have additional questions.

**Comment by fabiendem** [comment]
Thanks @AnastasiaKubova & @DmitriyKirakosyan!
