### ISSUE TITLE
https://appcenter.ms can not open

### ISSUE THREAD

**Issue by 0811002321** [microsoft/appcenter-sdk-android#1583]
### **Description**

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - e.g. Android 8.1.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 2 emulator, Samsung Galaxy S8 physical device
4. What third party libraries are you using?
    - example
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Could you please describe your issue in more detail? Please share reproducing steps and [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android)?

**Comment by 0811002321** [comment]
https://appcenter.ms can not open，I can not see Analytics and Crashes info
