### ISSUE TITLE
4.4.4 version not released

### ISSUE THREAD

**Issue by ivanorezac** [microsoft/appcenter-sdk-android#1620]
### **Description**

If appcenter-sdk-react-native is used, on building android it produces error:
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:4.4.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - file:/Users/name/.m2/repository/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - file:/Users/name/Code/react-native/node_modules/react-native/android/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - file:/Users/name/Code/react-native/node_modules/jsc-android/dist/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - https://dl.google.com/dl/android/maven2/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - https://www.jitpack.io/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
     Required by:
         project :app > project :appcenter
         project :app > project :appcenter-analytics
         project :app > project :appcenter-crashes

The iOS build works fine, as it matches the 4.4.4 version, therefore I suppose this is the issue with this package.

If installing the 4.4.3 RN version, everything works fine, as it simply links to the 4.4.3 version of Android/iOS.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install react native and try to build for android.

### **Details**

1. Which SDK version are you using?
    - 4.4.4 (RN) -  4.4.3 (Android) <- issue because 4.4.4 does not exist
2. Which OS version did you experience the issue on?
    - NA / During build
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - NA
4. What third party libraries are you using?
    - NA
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
NA

**Comment by aleksandr-dorofeev** [comment]
Hello @ivanorezac thank you for getting in touch with us!
This looks like a [duplicate](https://github.com/microsoft/appcenter-sdk-react-native/issues/976). 
Maven repository https://repo.maven.apache.org/maven2/com/microsoft/appcenter/reactnative/appcenter-react-native/ has been updated with the latest 4.4.4 release.  
Please check if it works now?
I am closing this issue. Feel free to reopen it if you have questions.
