### ISSUE TITLE
[Distribute] Consider opt-in for "Draw over apps" permission 

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1624]
**Is your feature request related to a problem? Please describe.**

When installing an update for the first time, the user is prompted for the "Draw over apps" permission:
- Previously called [`SYSTEM_ALERT_WINDOW`](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW).
- Replaced with Intent to `[Settings.ACTION_MANAGE_OVERLAY_PERMISSION](https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_OVERLAY_PERMISSION)`

As far as I know, this so that the app can restart automatically after the app installation: https://developer.android.com/guide/components/activities/background-starts

Snippets of code in the AppCenter library:

- https://github.com/microsoft/appcenter-sdk-android/blob/929f9ca66c624d5082c0da0f85ff8a0b0bbd8b64/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L1948-L1968
- https://github.com/microsoft/appcenter-sdk-android/blob/929f9ca66c624d5082c0da0f85ff8a0b0bbd8b64/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L1636-L1692

This is a bit overwhelming for the users since we're adding yet another permission.

**Describe the solution you'd like**

Is this permission really needed given the exceptions at: https://developer.android.com/guide/components/activities/background-starts#exceptions ?
> - The app has an activity that was started very recently.
> - The app called [finish()](https://developer.android.com/reference/android/app/Activity#finish()) on an activity very recently. This applies only when the app had either an activity in the foreground or an activity in the back stack of the foreground task at the time finish() was called.
> -  The app receives a [PendingIntent](https://developer.android.com/reference/android/app/PendingIntent) that is sent from a different, visible app.

You seem to send an intent to the app, so maybe this is enough?
https://github.com/microsoft/appcenter-sdk-android/blob/929f9ca66c624d5082c0da0f85ff8a0b0bbd8b64/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java#L186-L205

If it's really needed, would it be possible for the library to provide an opt-out via the API so we can decide or not if the permission is requested (and at the same time the auto restart)?

**Describe alternatives you've considered**

See above

**Additional context**

**Comment by DmitriyKirakosyan** [comment]
Hi @fabiendem , thank you for reporting this issue!
I created a work item on our board. We will inform you on the progress.

**Comment by MatkovIvan** [comment]
> You seem to send an intent to the app, so maybe this is enough?

It's not that part of code, but anyway - starting the app doesn't work without this permission.

> would it be possible for the library to provide an opt-out

Currently it's already optional - we'll try to install even if the customer just cancel this dialog.

> This is a bit overwhelming for the users since we're adding yet another permission.

I totally agree. We decided to remove it in future versions and post notification instead of opening the app.

**Comment by fabiendem** [comment]
Thanks @MatkovIvan!

> It's not that part of code, but anyway

🙃  I got lost in trying.

> Currently it's already optional - we'll try to install even if the customer just cancel this dialog.

Yes I noticed that.

> I totally agree. We decided to remove it in future versions and post notification instead of opening the app.

Awesome thank you 🚀

**Comment by fabiendem** [comment]
One note though, Android 13 will introduce...... "Notification permission": https://developer.android.com/about/versions/13/changes/notification-permission

**Comment by DmitriyKirakosyan** [comment]
The fix has been released!
I'm closing the issue, but feel free to reopen if you face it again.
