### ISSUE TITLE
AppCenter has stopped prompting users to install new version

### ISSUE THREAD

**Issue by snijsure** [microsoft/appcenter-sdk-android#1647]
### **Description**

AppCenter doesn't prompt users if there is new release is available
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install older version of the app 
2. Have latest versions available in app-center
3. Observe that folks running older version of the app never get prompted to upgrade the app.
4. Note this issue happens on Android 10, 11 & 12 versions.

### **Details**

1. Which SDK version are you using?
    - e.g. 4.4.5
2. Which OS version did you experience the issue on?
    - e.g. Android 29, 30,
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 2 emulator,  Google Pixel 4a
6. What third party libraries are you using?
    - example
7. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

[scrubbed.txt](https://github.com/microsoft/appcenter-sdk-android/files/9378326/scrubbed.txt)

Note: I have made sure AndroidManifest.xml contains

```
   <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />

```

I have also made sure we do call 

```
          Distribute.checkForUpdate();
          Distribute.setEnabledForDebuggableBuild(true);
```

As the attached log shows following logs:

08-18 17:05:22.864 17961 18042 V AppCenterDistribute: Calling https://api.appcenter.ms/v0.1/public/sdk/apps/****************************XXXXXX/releases/latest?release_hash=XXXXXX
08-18 17:05:22.864 17961 18042 V AppCenterDistribute: Headers: {}
08-18 17:05:23.425 17961 18042 V AppCenter: HTTP response status=404 payload={"code":"not_found","message":"Error: No public releases found for appId: XXXXX"}

One thing to note is appId that is logged is different from appId I see in our vault.  

The appId that appcenter logs is that obfuscated in some way or it should match what I see in our valut/build-config?

Anyway bottom-line is our users have stopped getting prompt to install updated APKs  and users end up testing with older releases that causes substantial churn. 

What other things I could try to diagnose this issue?

**Comment by DmitriyKirakosyan** [comment]
Hi @snijsure , thank you for reaching out to us!
This issue doesn't seem to be related to the SDK itself.
Please reach out to our [support team](https://docs.microsoft.com/en-us/appcenter/help). They will respond quickly and sync with the backend team to check if there is any existing issue.
Also, the [status pag](https://status.appcenter.ms/)e says that there are some issues in Distribute, which might affect you.

I'm closing this issue but feel free to reopen if you have any questions related to the SDK.

**Comment by pmarienfeld** [comment]
Hi @snijsure, currently I'm facing the same issue. Has the App Center support team been able to resolve this?

**Comment by Abhi011999** [comment]
Same here, any updates on this ?
