### ISSUE TITLE
Caused by java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads

### ISSUE THREAD

**Issue by hiteshsarsava** [microsoft/appcenter-sdk-android#1652]
SDK Versions used :

```
implementation "com.microsoft.appcenter:appcenter-analytics:4.0.0" 
implementation "com.microsoft.appcenter:appcenter-crashes:4.0.0"
implementation "com.microsoft.appcenter:appcenter-distribute:4.0.0"
```

![image](https://user-images.githubusercontent.com/16486943/193535617-d63b22a2-8df3-460c-a5de-25f288e213e5.png)
![image](https://user-images.githubusercontent.com/16486943/193535803-6d645213-6e5b-41d2-9d53-552d86589dba.png)
![image](https://user-images.githubusercontent.com/16486943/193535934-eca4473f-e993-4a31-8a9b-36c653bf05e2.png)

**Comment by DmitriyKirakosyan** [comment]
Hi @hiteshsarsava , please update the AppCenter SDK to 4.1.1 or higher. It is recommended to use the latest version (currently 4.4.5). This crash was fixed in https://github.com/microsoft/appcenter-sdk-android/pull/1508.
It is happening because the Download Manager is disabled.
