### ISSUE TITLE
Support for multiple ABIs?

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-sdk-android#1668]
**Is your feature request related to a problem? Please describe.**

Hi, I am pretty sure the answer is no, but I want a confirmation.
Does AppCenter Distribute for Android supports multiple abis (armeabi-v7a, arm64-v8a, etc...)?
Or do we have to distribute the Universal APK if we want to use AppCenter Distribute on multiple archs.

**Describe the solution you'd like**
Being able to upload multiple APKs with different ABI versions

**Describe alternatives you've considered**

Distribute the universal APK, larger file.

**Additional context**
N/A

**Comment by DmitriyKirakosyan** [comment]
Hello @fabiendem , sorry for late reply, but we don't support distributing multiple abis at this moment. Mostly it depends on the backend side.
The feature was already discussed here https://github.com/microsoft/appcenter/issues/99.

I'm closing this as duplicate, but feel free to bump the thread I mentioned above.
