### ISSUE TITLE
App is not automatically closing after the update.

### ISSUE THREAD

**Issue by ayyappantringapps** [microsoft/appcenter-sdk-android#1671]
**Description**

For almost the majority of the devices, the app was closed after an update. But on some devices, it's not closed after an update.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.open app and install the new version.

### **Details**

1. Which SDK version are you using?
    - 5.0.0
2. Which OS version did you experience the issue on?
    - Android 13
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Samsung S21
4. What third party libraries are you using?
    - many libraries
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

**Comment by AnatolyPristensky** [comment]
Hello @ayyappantringapps and thank you for getting in touch with us. 
I'm working on testing this behaviour, and will update this thread with results.

**Comment by AnatolyPristensky** [comment]
@ayyappantringapps, could you please share a logs using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)`?

**Comment by MikhailSuendukov** [comment]
I close the issue due to lack of activity. If your problem is still relevant, or you have any questions, feel free to contact us.
