### ISSUE TITLE
DistributeListener interface methods are not called on React native Android.

### ISSUE THREAD

**Issue by suhaspathak** [microsoft/appcenter-sdk-android#1672]
Created the React Native project. We are native approach implementing iOS and Android distribution for release builds to end user devices. 

We are implemented App Center Distribute for the Android In-app updates but following methods never called:

1. public boolean onReleaseAvailable(Activity activity, ReleaseDetails releaseDetails)
2.  public void onNoReleaseAvailable(Activity activity) 

Please let me know how to fix this issue.

**Comment by MikhailSuendukov** [comment]
Hi @suhaspathak  and thanks for contacting us. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here. It will also be very helpful if you attach a small demo application that reproduces your error.

**Comment by DmitriyKirakosyan** [comment]
@suhaspathak , Distribute isn't supported for ReactNative projects. The active feature request https://github.com/microsoft/appcenter-sdk-react-native/issues/225
