### ISSUE TITLE
Possibility of accessing release number and using it in app

### ISSUE THREAD

**Issue by alvindizon** [microsoft/appcenter-sdk-android#1675]
Is it possible to access the release number of our app and display it in our app? See screenshot below to see what I'm referring to:

![Screenshot 2023-03-15 at 9 57 00 AM](https://user-images.githubusercontent.com/30955662/225171420-69b0aa7b-291c-4b3e-a3a6-677a0a2bc115.png)

 We'd like to have the ability to differentiate among different builds.

**Comment by MikhailSuendukov** [comment]
Hi @alvindizon  and thanks for contacting us. Unfortunately, we do not support this scenario. Therefore, I am closing this issue, but if you have any further questions, feel free to reopen it.
