### ISSUE TITLE
Add support for Android 11's ActivityManager.getHistoricalProcessExistReasons API

### ISSUE THREAD

**Issue by peitschie** [microsoft/appcenter-sdk-android#1683]
**Is your feature request related to a problem? Please describe.**
AppCenter's SDK crash reports miss various problematic app termination reasons, meaning that even with crash reporting enabled a lot of app restarts never log any crashes or issues (e.g., due to excessive power usage, dependency process died, app frozen, etc.).

**Describe the solution you'd like**
Android 11 has added an `ActivityManager.getHistoricalProcessExistReasons()` API that can be used to retrieve the termination status of the app on next restart: https://developer.android.com/about/versions/11/features#app-process-exit-reasons

Android 12 has even added the ability to retrieve an associated tombstone file in the event of a native crash: https://developer.android.com/about/versions/12/features#provide_apps_direct_access_to_tombstone_traces

It would be fantastic to have this SDK grow support for these features on supported phones.

**Describe alternatives you've considered**
No other solutions considered... this seems to be the only way to capture these exit conditions.

**Additional context**
N/A

**Comment by peitschie** [comment]
Here's the equivalent feature present in Crashlytic's crash reporting: https://github.com/firebase/firebase-android-sdk/pull/2602

**Comment by aleksandr-dorofeev** [comment]
Hello @peitschie 
Thanks for the feature request! Unfortunately we don't have an ETA, but contribution is always welcome :)
