### ISSUE TITLE
Google Play - Intent Redirection vulnerability

### ISSUE THREAD

**Issue by noturtype** [microsoft/appcenter-sdk-android#1686]
Google is alerting to the following with a target to remove apps from Google Play.

com.microsoft.appcenter.distribute.AppCenterPackageInstallerReceiver.onReceive

**Comment by aleksandr-dorofeev** [comment]
Hi @noturtype, thanks for getting in touch with us!
Could you provide more context, such as a full alerting about removing apps.
Also note that the `AppCenterPackageInstallerReceiver` class does not exist in the project.

**Comment by noturtype** [comment]
Hi @aleksandr-dorofeev, it appears upon submission, we're getting flagged for an Intent Redirection vulnerability:
________
"Intent Redirection
Your app contains an Intent Redirection vulnerability. Please see [this Google Help Center article](https://support.google.com/faqs/answer/9267555) for details.

com.microsoft.appcenter.distribute.AppCenterPackageInstallerReceiver.onReceive
sv:deadline:07/02/2023"
_________

This is a NativeScript app using a plugin, nativescript-microsoft-appcenter, who's gradle lists a single dependency to 4.4.2 com.microsoft.appcenter. I updated the gradle yesterday to 5.0.1 and I removed the implementation of com.microsoft.appcenter:appcenter-distribute since we are not using any of the distribute functionality of AppCenter. Resubmitted on Console and received the same alert. 
I too am unclear why this class AppCenterPackageInstallerReceiver is being flagged. I did just pull down and searched 5.0.1 and do not see it. A Google search returns a single hit to: https://github.com/microsoft/appcenter-sdk-android/issues/1624 where the class name appears. Perhaps I'm not doing something correctly, I'm not very fluent in this environment.

**Comment by aleksandr-dorofeev** [comment]
I apologize for the misunderstanding.
As I understand it, you are publishing the application with the `distribute` module, which you should not do.
We have a separate `distribute-play` module with a stubbed API for publishing to Google Play.
You can find its addition in the [documentation](https://learn.microsoft.com/en-gb/appcenter/sdk/distribute/android#prepare-your-google-play-build)
You can also check similar issues: https://github.com/microsoft/appcenter-sdk-android/issues/1614
