### ISSUE TITLE
Ability to disable App Update notification

### ISSUE THREAD

**Issue by Saravana-Gunaseelan** [microsoft/appcenter-sdk-android#1700]
### **Description**

I recently upgraded appcenter version from 4.3.1 to 5.0.2. Everything works as expected except there is a notification that appears whenever there is an app update. The notification shows `<App name> has been updated installed.`. This occurs not only when app is updated through appcenter but also when app is updated through our own appstore. Is there a way to disable this notification?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add appcenter distribute library to the app. Install it.
2. Increment the app versionName and versionCode. Install this new incremented app build.
3. Observe the notification generated by the app.

### **Details**

1. Which SDK version are you using?
    - 5.0.2
2. Which OS version did you experience the issue on?
    - Android 12
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical device (LumePad 2)

**Comment by MikhailSuendukov** [comment]
Hello and thank you for reaching out to us. Sending this notification is part of the functionality of the Distribute module, and we currently do not have the functionality to disable these notifications.
