### ISSUE TITLE
No crash attachments and analytics events 

### ISSUE THREAD

**Issue by JumpyWizardEni** [microsoft/appcenter-sdk-android#1707]
### **Description**

We have an application that receives about 200,000 crash events and non-fatal errors every day. We noticed that most of the attachments in crashes and non-fatal errors do not come, a similar situation with Analytics and events.

At the same time, in the test build for a small number of developers, all attachments and events are displayed. For example, events number in test build about 5 times more than in production.

We do not exceed the quotas specified in the documentation. Maybe there are implicit limits on the number of all events (crash reports, analytics, etc.), and attachments and events are discarded as least priority?

### **Repro Steps**

We couldn't reproduce this bug. Bug only in our production app, in debug build all attachments and events are displayed in the AppCenter.

We thought it might be because of obfuscation, but the bug is not reproduced on a sample project with obfuscation.

### **Details**

1. Which SDK version are you using?
    - 5.0.2
2. Which OS version did you experience the issue on?
    - every version starting with Android 7.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - not device specific

**Comment by DmitriyKirakosyan** [comment]
Hi @JumpyWizardEni , this can happen because of the limited storage capacity. If the storage is full, the SDK will remove older logs with lower priority, ordering by priority, then by age.
Try to increase the storage size using the [Storage Size API](https://learn.microsoft.com/en-us/appcenter/sdk/other-apis/ios#storage-size).

**Comment by JumpyWizardEni** [comment]
Thanks for your answer. @DmitriyKirakosyan does it mean that analytics events have lower priority than crashes and error?
However, we store attachments in a separate file, it cannot be affected by the logic and limitations of Appcenter. The file itself is limited to 2 MB, which is much less than the limit specified in the documentation (7 MB).

**Comment by JumpyWizardEni** [comment]
I tried to send logs from a simple application to which only appcenter is connected, and received only part of the crashes without attachments. Apparently, we still exceed the specified limits, although it seemed that separate restrictions should apply to attachments. I think the issue can be closed

**Comment by DmitriyKirakosyan** [comment]
> does it mean that analytics events have lower priority than crashes and errors

Yes, analytics has lower priority.

> However, we store attachments in a separate file, it cannot be affected by the logic and limitations of Appcenter. The file itself is limited to 2 MB, which is much less than the limit specified in the documentation (7 MB).

Every log is temporarily stored in storage before being sent to the backend. This includes attachment logs, which are saved in storage even if they originated from a file.
