### ISSUE TITLE
java.lang.InternalError: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by amaanshaw** [microsoft/appcenter-sdk-android#1725]
### **Description**
We have noticed the following crash appearing on AppCenter in our production environment:
![image](https://github.com/microsoft/appcenter-sdk-android/assets/162335829/8aeaec48-c11c-4ede-9d12-b9dde4aef1a6)

Unfortunately, we don't have much information in regards to what causes the crash to happen. All we can ascertain from the log is something is causing a new thread to spin up during the shutdown of the app. Please let us know if there is anything else we can provide to help resolve this.

### **Details**
1. Which SDK version are you using?
    - 4.4.5
    - We will be updating to 5.0.4 in our next release (6-8 weeks time)
2. Which OS version did you experience the issue on?
    - Android 10
    - Android 9
    - Android 7.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
These devices have been reported by AppCenter with the crash:
    - Moto e(7)
    - Moto e(7) power
4. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here: Sadly as this was a crash in production we are unable to get any verbose logs.

**Comment by MikhailSuendukov** [comment]
Hello, and thank you for reaching out to us!
Upon investigating this issue, it seems that this problem typically arises when an `HttpClient` is instantiated as the application is in the process of shutting down. This situation might occur, for instance, during the execution of your unhandledExceptionHandler (links: https://github.com/OneSignal/OneSignal-Android-SDK/issues/443, https://stackoverflow.com/questions/45584141/unknown-bug-thread-starting-during-runtime-shutdown). 
Could you please review your `setDefaultUncaughtExceptionHandler` to verify if it aligns with these circumstances? 
For a more in-depth analysis of this issue, it would be helpful to get a simple demo application that reproduce this error, along with steps to reproduce it.

**Comment by amaanshaw** [comment]
Hello, thanks for the speedy response!

Sorry I should have clarified earlier we have a Unity C# project with a native implementation of the SDK. We register to `AppDomain.CurrentDomain.UnhandledException` on the managed side. When this is fired, we call our native implementation of the AppCenter SDK to trigger `Crashes.trackError` with the throwable.

At the moment, we are unsure how this crash is being triggered but I can do some more investigation.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
