### ISSUE TITLE
Avoid in-app update page for distribution

### ISSUE THREAD

**Issue by javitosanchez** [Microsoft/AppCenter-SDK-Android#600]
Hi,

Is it possible to avoid in-app update registration the first time the app is launched? I'm prototyping the distribution of an app for more than 20000 devices and I'm figuring out if there is a way to install the app the first time without doing it from app center.

I tried `StorageHelper.PreferencesStorage.putString(PREFERENCE_KEY_DISTRIBUTION_GROUP_ID, "<group_id>");` but didn't work :-)

**Comment by guperrot** [comment]
Hi, you can call `Distribute.setEnabled(false)` right after `AppCenter.start`.
Once your app is ready to open browser call `Distribute.setEnabled(true)` (needs to happen after `AppCenter.start`).

The calls to `Distribute.setEnabled` are persisted in storage.

**Comment by guperrot** [comment]
Closing this unless we have feedback from you @javitosanchez, thanks for using App Center.
