### ISSUE TITLE
TargetFrameworkVersion for Microsoft.AppCenter.Analytics.Android.Bindings greater than that of your project

### ISSUE THREAD

**Issue by nathanielcook** [Microsoft/AppCenter-SDK-Android#621]
When building the Android app with AppCenter NuGets version 1.3.0 added to our Android project, we get warnings like the following:

> Warning XA0105: The $(TargetFrameworkVersion) for Microsoft.AppCenter.Analytics.Android.Bindings.dll (v8.0) is greater than the $(TargetFrameworkVersion) for your project (v7.1). You need to increase the $(TargetFrameworkVersion) for your project. (XA0105)

This is basically the same bug that was opened almost a year ago [on bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=56648). There is a sample project attached to that bugzilla demonstrating the problem. (See attachment named "updated sample project with new repro".)

There is no way to prevent this warning from showing up, aside from upgrading the target framework of our project. (We're not ready to do that yet, because of [changes to backgrounding in Android Oreo](https://blog.xamarin.com/replacing-services-jobs-android-oreo-8-0/).) Is there a reason the AppCenter dlls needs to target Android 8.0? Why can't they target an early framework version for compatibility?

**Comment by nathanielcook** [comment]
Here is a new sample project, for use with Visual Studio for Mac. This sample project uses version 1.3.0 of the AppCenter NuGets.

[TargetFrameWarn3.zip](https://github.com/Microsoft/AppCenter-SDK-Android/files/1721835/TargetFrameWarn3.zip)

**Comment by guperrot** [comment]
Hi this is not the right repository to report issues on the [.NET SDK](https://github.com/Microsoft/AppCenter-SDK-Dotnet). This one is for Android Java.

Also Target Framework version is different from target sdk version, you can update target framework and keep target sdk version to 7.1 (in Android application settings).

We cannot change target framework as we need to call some APIs of Android 8 when available.

Plus this is just a warning and will not prevent you from using the SDK.

**Comment by nathanielcook** [comment]
Apologies for reporting this on the wrong repo. 

My understanding based on previous research was that the target framework version should match the target sdk version. In fact, I get [a different warning](https://stackoverflow.com/questions/35041378/warning-xa4211-in-xamarin) when I change the target framework version to 8.0 and leave the target sdk version at 7.1. That said, I do see in the documentation [here](https://developer.xamarin.com/guides/android/application_fundamentals/android-api-levels/#framework) that the "target Android version" (aka target SDK version) can be less than the target framework version. (Why on earth is there a warning that we have [no way to suppress](https://forums.xamarin.com/discussion/88322/suppress-xamarin-android-manifest-build-warning-xa4211)?)

Given that you guys need to target framework 8.0, and especially given that this is the wrong repo, closing this issue. Thanks

**Comment by guperrot** [comment]
There is a good chance we will keep increasing target framework version whenever we need to call a new API conditionally to support new Android versions.

Regarding the other field, the real targetSdkVersion that gets into your manifest at build time (not in project manifest), Google Play will make it mandatory to targetSdkVersion 26 (android 8.0) as soon as Android 9 is released to all. And each time there will be a new major version, you will need to target at least major version - 1. This typically happens in September each year. 

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html
