### ISSUE TITLE
Eclipse support

### ISSUE THREAD

**Issue by ssniteman** [Microsoft/AppCenter-SDK-Android#633]
Hi,

I am trying to add App Center's SDK to an old app using Eclipse. Gradle does not seem to work correctly with the imports.

Therefore, I took the appcenter-release.aar, appcenter-analytics-release.aar, and appcenter-crashes-release.aar files, unpacked them, took the "com" folders, and repackaged those as .jar files to them manually import them into the lib folder.

Analytics and crashes seemed to have imported correctly; however, the release file did not. I tried to package the "com" file along with the "proguard.txt" file as well and that did not seem to work.

Does anyone have any insight on this or could help?

Thank you!

**Comment by jaelim-ms** [comment]
Hello @ssniteman,

Unfortunately App Center SDK doesn't support Eclipse as described in [AppCenter Doc](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android) and we haven't tried the SDK on Eclipse so we strongly recommend you to use Android Studio for your app.
If you have any further questions, please let me know.

Thanks!
Jae.

**Comment by guperrot** [comment]
Hi, Google [ended support](https://android-developers.googleblog.com/2016/11/support-ended-for-eclipse-android.html) for Eclipse for Android and thus we cannot support Eclipse for our library. Sorry for the inconvenience it causes.
