### ISSUE TITLE
Errors in Google Play Pre-launch report due to linking error

### ISSUE THREAD

**Issue by tvdwal** [Microsoft/AppCenter-SDK-Android#686]
https://github.com/Microsoft/AppCenter-SDK-Android/blob/9dab6f7439b867fa5ddec2c786e46ab794cc97ac/sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/InstrumentationRegistryHelper.java#L20

The error is discussed in this forum post --> https://forums.xamarin.com/discussion/comment/331161/#Comment_331161 

When uploading an APK that includes Microsoft AppCenter we get a linker error that the getArguments function can not be found. Tried all the possible solutions described here ( https://xamarinhelp.com/xamarin-linker/ ) but without success. This is because we can't access InstrumentationRegistry from the Xamarin code as there seems to be no wrapper for the android.support.test jar.

Could you make sure this library gets included in the Microsoft Appcenter Android SDK?
https://github.com/Microsoft/AppCenter-SDK-Android/blob/9dab6f7439b867fa5ddec2c786e46ab794cc97ac/sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/InstrumentationRegistryHelper.java#L4

**Comment by MatkovIvan** [comment]
Hi @tvdwal,

Thanks for getting in touch!

#667 should fix this issue. Could you please try the latest version of SDK?

Best,
Ivan

**Comment by tvdwal** [comment]
This solved it. Thanks Ivan!
