### ISSUE TITLE
Android not attach file report crash appcenter

### ISSUE THREAD

**Issue by hoaphuong1311** [Microsoft/AppCenter-SDK-Android#754]
I have a issue attach file sqlite send to report crash app center on android
It's work on android device android 5 but not work on device android 7

           ErrorAttachmentLog textLog = ErrorAttachmentLog.attachmentWithText(stringBuilder.toString(), "LogInfo.txt");
            ErrorAttachmentLog databaseLog = ErrorAttachmentLog.attachmentWithBinary(convertDataBaseToBinary(), "Ezyhaul.db", "application/octet-stream");
            return Arrays.asList(textLog, databaseLog);
Help me fix it

**Comment by guperrot** [comment]
Hi, please don't erase the issue template next time.

Please share the full listener code and make sure it is called **before** AppCenter.start.

If that is the case, [adjust SDK log level to verbose](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level) then build/run the app and reproduce the issue.

Then either go to logcat in Android Studio or run `adb bugreport`, if you choose to look at logs in logcat, extract all logs with tag starting with AppCenter and attach them somewhere. For the second  option it produces a zip.

If you don't want to share logs publicly, create a ticket to share logs using the chat button in https://appcenter.ms and reference this issue.

**Comment by guperrot** [comment]
Hey! 

We haven’t heard from you in a while, so I am going to go ahead and close this ticket. Should you still have any questions, you can write a message here and we will reopen the ticket or if you prefer you can create a new ticket. Please don’t hesitate to contact us again.

Thanks for using App Center!

**Comment by vgrigorjeva** [comment]
Hi! Im having the same issue when getting crash report for android. Attachment and events before the crash are not shown for android, but are shown for iOS (im using react-native). `    Crashes.setListener({
      shouldProcess: function(report) {
        return true;
      },
      getErrorAttachments(report) {
        return [
          ErrorAttachmentLog.attachmentWithText(
            `Get error attachments for report with id: ${report.id}'`
          )
        ];
      }
    });`

**Comment by bmourat** [comment]
Hi @vgrigorjeva 
Try adding `fileName` parameter to `attachmentWithText` method call.
