### ISSUE TITLE
Expose default notification sound for in-app push retrieval

### ISSUE THREAD

**Issue by janpieterz** [microsoft/appcenter-sdk-android#755]
### **Description**

It'd be great if the SDK exposes a method or option to trigger the default notification sound when receiving the notification in-app.

**Comment by jwallra** [comment]
I linked to here from the wrong issue, ignore the reference 😅

**Comment by guperrot** [comment]
On Android 8, the default notification template has sound enabled.
To push sound to older devices, you can add `sound: true` as custom data.

**Comment by janpieterz** [comment]
Not the key, I'd like to be able to play the platform's default notification sound when we receive the notification in-app.

In our case it's much like a message from a person, for example in Whatsapp or Messenger, and the ability to play a quick sound to highlight the little toast we show in the app would be great.

Of course adding a dependency on react-native-sound or something else is an option, or writing ourselves, but it'd be super convenient to have `Push.PlayNotificationSound()` or something.

**Comment by elamalani** [comment]
@janpieterz Thanks for using App Center. We don't plan to support this feature right now but will keep this issue open for visibility and let you know once we decide to work on it in the SDK.

**Comment by AnastasiaKubova** [comment]
Hi there!
The App Center Push module has been removed from App Center SDK in the [4.0.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.0.0) version so we are closing this feature request.

As an alternative to App Center Push, we recommend you migrate to [Azure Notification Hubs](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-overview) by following the [Push Migration Guide](https://docs.microsoft.com/en-us/appcenter/migration/push/).
