### ISSUE TITLE
Quotation symbols break gradlew install

### ISSUE THREAD

**Issue by annakocheshkova** [Microsoft/AppCenter-SDK-Android#827]
### **Description**

Can not run `gradlew install`.

### **Repro Steps**
1. Checkout the latest version of the SDK.
2. Run `gradlew install`

Face 
![image](https://user-images.githubusercontent.com/34677812/46530523-b6af5080-c8a2-11e8-90d4-49b72ed62335.png)

Comment: wrong quotation symbols in `DeviceExtension`, `UserExtension`, `OsExtension`:
![image](https://user-images.githubusercontent.com/34677812/46530626-0d1c8f00-c8a3-11e8-9203-8c9f0efe80f7.png)

### **Details**

Which SDK version are you using?
    - develop branch
OS
    - Windows 10 Enterprise 64-Bit

**Comment by achocron** [comment]
Thanks for bringing that up! We have a PR that should fix this, so look out for our next release.
