### ISSUE TITLE
Use java.util.Logger instead of android.util.Log

### ISSUE THREAD

**Issue by sixpi** [microsoft/appcenter-sdk-android#844]
### **Use java.util.Logger instead of android.util.Log**

The SDK currently uses `android.util.Log`, which prints directly to logcat without any mechanism for redirecting to other destinations. If `java.util.Logger` was used instead, then client apps get control over where logs are output to - in our app, we are required to print nothing to logcat; instead logs are redirected to a file, which are uploaded when a user reports an issue from within the app (with consent of course). 

Seems like just replacing the user of `Log.*` methods with the appropriate `Logger.*` methods in `AppCenterLog` should be sufficient.

**Comment by ElektrojungeMS** [comment]
Hey @sixpi,

thank you for this feature request. I've tagged it accordingly and will forward this to our PM.

Best,
Benjamin

**Comment by sixpi** [comment]
Has this been worked on?

**Comment by DmitriyKirakosyan** [comment]
Hi guys,

Thank you for bumping this feature request!
I'll discuss the issue within the team and we will decide if we should prioritze it.

If it is a blocker for you, please feel free to prepare a PR and test the changes on a demo app.
We will review and merge it if everything works as expected.

Thanks.

**Comment by AnastasiaKubova** [comment]
Hi! The feature [has been released](https://github.com/microsoft/appcenter-sdk-android/releases/tag/4.4.1), so I'm going to close this issue. Feel free to reopen it if you will have additional questions.
