### ISSUE TITLE
Track exception is missing

### ISSUE THREAD

**Issue by poldz123** [microsoft/appcenter-sdk-android#933]
When does the `trackException` going to be implemented. Seems that it is not yet in the android sdk for app center.

Version: 1.11.2

**Comment by blparr** [comment]
Hello! Unfortunately we don't have a timeline for that yet. We only have support for exceptions in both Xamarin and Unity.

**Comment by yuecelm** [comment]
This is also a blocker in Flutter apps to use AppCenter for crash reporting.

**Comment by yuecelm** [comment]
Flutter apps are written in Dart. You could provide an additional SDK for Dart (like Sentry). But its also possible to embed native code for iOS or Android in Flutter. If you provide a `trackException`-API for iOS and Android it could be enough to support App Center for crash reporting in Flutter. Just keep in mind that dart exceptions/errors are not the same as iOS/Android exceptions/errors, but the dart exception/error could be provided as String (including the stacktrace). I am just not sure how compatible this solution is with your current system.

**Comment by poldz123** [comment]
+1

**Comment by winnieli1208** [comment]
Hi all,

Thanks for the feedback. For those with feature requests (such as tracking handled exceptions for Android apps), please submit an issue in our public App Center repo or give an existing feature a +1: https://github.com/Microsoft/appcenter/issues

This will help our team prioritize the features accordingly. Thanks!

**Comment by humblerookie** [comment]
I created something like this with their latest SDK.

package com.microsoft.appcenter.crashes

/**
 * Created by Anvith on 2019-07-24.
 */

```
class CrashesWrapper {


    companion object {

        fun trackException(t: Throwable) {
            Crashes.trackException(t)
        }
    }
}
```
Although this just is a workaround for the sdk restriction, not sure whether the backend handles them.

**Comment by winnieli1208** [comment]
@humblerookie no updates at the moment. Our team is busy working on the features listed in our iteration plan. Please give the feature request a +1 in our App Center repo to help our team prioritize: https://github.com/microsoft/appcenter/issues/432

I'll also post any updates there. Thanks!

**Comment by lukaville** [comment]
@winnieli1208 do you have any updates on this issue? It's a blocker for us, we used this feature extensively in HockeyApp and we can't migrate to app center so most likely we will have to use another crash reporting tool :(

**Comment by winnieli1208** [comment]
Hi @lukaville - no updates yet but our team just kicked off some threads to discuss how to best implement this. I'll follow up when I have an estimated target date. Thanks for your patience!

**Comment by Jamminroot** [comment]
@lukaville @poldz123 we have this feature tracked, but there are no ETAs we can provide yet.

**Comment by guperrot** [comment]
The SDK version 2.5.0 has been released and contains `trackError` API.
The docs for this new API can be found at https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#handled-errors.
