### ISSUE TITLE
Issue sending logs on Internal wifi network to App center

### ISSUE THREAD

**Issue by sonu1** [Microsoft/AppCenter-SDK-Android#941]
### **Description**

Having Issues sending logs to App Center on SSID network. 
**Location :**  appcenter\utils\NetworkStateHelper.javaNetworkStateHelper.java
Class NetworkStateHelper  ->   Method reopen() --> public void onAvailable(Network network) method is not called when the SSID network is connected. Is there a work around for this.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Connecting to SSID network.
2. appcenter\utils\NetworkStateHelper.javaNetworkStateHelper.java.
Class NetworkStateHelper  ->   Method reopen() --> public void onAvailable(Network network) method is not called when the SSID network is connected. Is there a work.

### **Details**

1. Which SDK version are you using?
    1.11.2
2. Which OS version did you experience the issue on?
    - e.g. Android 6.0.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
      all devices tested on.
4. What third party libraries are you using?
    NA
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

D/AppCenter: Call triggered with no network connectivity, waiting network to become available...
D/AppCenter: Call triggered with no network connectivity, waiting network to become available...
D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0
D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0

**Comment by sonu1** [comment]
Hi @MatkovIvan , can you please advice regarding the timeline for this fix. And why is this happening?  Thanks.

**Comment by MatkovIvan** [comment]
Hi @sonu1,

You can review the fix [here](https://github.com/Microsoft/AppCenter-SDK-Android/pull/943) if you are interested.

As I wrote to you in intercom, we release the SDKs every month, but I'm not sure that this fix will be included in the February one.

Thanks,
Ivan

**Comment by MatkovIvan** [comment]
The fix has been merged and will be available in the March release of the SDK.
Keeping issue open until release with the fix.

**Comment by guperrot** [comment]
If you are interested in testing a pre-release of the SDK you can add:

```
repositories {
    maven {
        url  "https://dl.bintray.com/vsappcenter/appcenter-snapshot" 
    }
}
```

To the same gradle file you are adding the SDK dependency and then change version to: `1.11.4-0+2e7270c4` which contains a fix for network state management.

**Comment by chethanreddyvelverti** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
