### ISSUE TITLE
Question about App Center Distribute React Native

### ISSUE THREAD

**Issue by Jalson1982** [Microsoft/AppCenter-SDK-Android#944]
Hello. Is it possible to use App Center Distribute – In-app updates with react native app? I am trying to find in docs but I am not sure is it working?

**Comment by dhei** [comment]
Hi @Jalson1982,

We don't support In-app updates in RN SDK at the moment. See https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/225 for tracking of this feature request.

**Comment by dhei** [comment]
@Jalson1982,

The keystore not found error is probably not related to App Center RN SDK. When you configured App Center Build signing, have you uploaded the keystore file and configured keystore password correctly? Checkout our documentation on Android code signing at https://docs.microsoft.com/en-us/appcenter/build/android/code-signing.

Please contact our dedicated support team via intercom (the blue button on App Center portal) for any App Center Build issues.

Thanks.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue.
Please reopen/comment if you have more questions or run into this again.
