### ISSUE TITLE
Problem with AppCenter In-App Updates

### ISSUE THREAD

**Issue by dotfig** [Microsoft/AppCenter-SDK-Android#948]
**What App Center service does this affect?**
AppCenter In-App Updates

**Describe the bug**
When releasing a new version of my app, users who are on Android version 7.0 can upgrade within the application but users who are on Android version 5.1 cant.

**Expected behavior**
I expect all Android versions to be able to in-app update. This was previously never an issue.

**Smartphone (please complete the following information):**
 - GT-500 / GT-500V
 - Android 5.1 / Android 7.0

-developed using Xamarin with minSdkVersion=17 and targetSdkVersion=27

**Comment by MatkovIvan** [comment]
Hi @dotfig,

Thanks for getting in touch!
Could you please [enable verbose logging](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level) for your and share the logs from these devices?

Thanks,
Ivan

**Comment by dotfig** [comment]
[v51.txt](https://github.com/Microsoft/AppCenter-SDK-Android/files/2865702/v51.txt)
[v7.txt](https://github.com/Microsoft/AppCenter-SDK-Android/files/2865703/v7.txt)

**Comment by MatkovIvan** [comment]
@dotfig The log level affect only on logging into a local console (logcat). The SDK doesn't send debug logs to the backend. So, I asked for _device_ (logcat) logs, not the logs from the portal.

> I put it before `AppCenter.Start("...");`

That's right.

**Comment by dotfig** [comment]
sorry for the late response @MatkovIvan but is there a way to enable in-app updates through debug mode? When I run my application in Debug mode, I get this
```` 
02-22 14:56:10.016 I/AppCenterDistribute(20608): Not checking in app updates in debug. 
````

**Comment by jaelim-ms** [comment]
No, we don't support in-app update in debug by design.

**Comment by dotfig** [comment]
Have you guys heard anything about in-app updates not working for specific versions of AppCenter SDK on specific versions of Android OS

**Comment by jaelim-ms** [comment]
Yes. We do. Can you give me your device details?

**Comment by dotfig** [comment]
I am on an Amobile GT-500 device that is running Android v5.1. We distribute our application to our 100 of these devices. We have noticed that the passed few mandatory release we have done, the in-app updates do not work on these devices with this Android version.

**Comment by dotfig** [comment]
@jaelim-ms  It seems like the new apk file is not being downloaded properly

**Comment by dotfig** [comment]
Please move this issue to AppCenter-SDK-DotNet

**Comment by dotfig** [comment]
### Update
Apparently this is a known issue with migrating from HockeyApp SDK to AppCenter SDK. Not really sure what the difference is between the Android OS versions but the team at AppCenter is working on a migration strategy for this.

**Comment by NandanPedemane** [comment]
Hi tried to ass in app updates in the app but its showing "app not installed.The package appears to be corrupt

**Comment by NandanPedemane** [comment]
In app update downloads the new update but again showing update screen like infinite loop.Anybody facing this issue?

**Comment by Jamminroot** [comment]
Hey, @NandanPedemane, that looks like a different issue. Pleaes open a separate issue, so that we can have a look and help you out, and not mix two separate conversations and track the conversation easier.

**Comment by ExtremeKaos** [comment]
Still have infinite loop when update in android device 5.1, any workarround for this ?

**Comment by MatkovIvan** [comment]
@ExtremeKaos I guess #1318 is the right thread for it. It looks like a few people are affected, but we still don't have reproduction and logs.
Please add additional details (logs, repro steps, sample project) there, it will be very helpful for our investigation. Thanks.
