### ISSUE TITLE
Where is LoginManager from HockeyApp SDK?

### ISSUE THREAD

**Issue by BenjaminZaiser** [microsoft/appcenter-sdk-android#952]
As HockeyApp will be moved completely to AppCenter later this year I would expect that AppCenter provides the same features as HockeyApp. But I cannot find the LoginManager in the AppCenter SDK, see https://support.hockeyapp.net/kb/client-integration-android/authenticating-users-on-android.

Is there a plan to integrate this feature later this year before HockeyApp will be shutdown?
So I can publish my app today by using HockeyApp and move to AppCenter as soon as it is available.

Or will AppCenter not support this feature anymore? Which would be very sad, because then I have to implement it on my own which can be quite cumbersome.

Thanks for some feedback
Ben

**Comment by elamalani** [comment]
@BenjaminZaiser Authentication works differently in App Center as compared to HockeyApp. We have simplified the in-app updates experience in App Center if you want to let your users install a new version of the app. So you get user authentication automatically if you want to use App Center Distribute service with in-app updates. Please refer to this [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android). Could you tell me which authentication method are you currently using in HockeyApp?
