### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked DatabaseManager.java, line 410 Crash

### ISSUE THREAD

**Issue by kevoroid** [Microsoft/AppCenter-SDK-Android#957]
Hey,
Im receiving this error/crash since the latest update to 1.11.0 for Android.

> com.microsoft.appcenter.utils.storage.DatabaseManager.getMaxSize
DatabaseManager.java, line 410
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)

and the stack trace from AppCenter web portal:

`  android.database.sqlite.SQLiteConnection.nativeExecuteForLong SQLiteConnection.java
    android.database.sqlite.SQLiteConnection.executeForLong SQLiteConnection.java:598
    android.database.sqlite.SQLiteSession.executeForLong SQLiteSession.java:652
    android.database.sqlite.SQLiteStatement.simpleQueryForLong SQLiteStatement.java:107
    android.database.DatabaseUtils.longForQuery DatabaseUtils.java:825
    android.database.DatabaseUtils.longForQuery DatabaseUtils.java:813
    android.database.sqlite.SQLiteDatabase.getMaximumSize SQLiteDatabase.java:902
    com.microsoft.appcenter.utils.storage.DatabaseManager.getMaxSize DatabaseManager.java:410
    com.microsoft.appcenter.persistence.DatabasePersistence.putLog DatabasePersistence.java:275
    com.microsoft.appcenter.channel.DefaultChannel.enqueue DefaultChannel.java:674
    com.microsoft.appcenter.analytics.Analytics$8.run Analytics.java:781
    com.microsoft.appcenter.AbstractAppCenterService$4.run AbstractAppCenterService.java:301
    com.microsoft.appcenter.AppCenter$7.run AppCenter.java:703
    android.os.Handler.handleCallback Handler.java:739
    android.os.Handler.dispatchMessage Handler.java:95
    android.os.Looper.loop Looper.java:159
    android.os.HandlerThread.run HandlerThread.java:61`

**Comment by MatkovIvan** [comment]
Hi @kevoroid,

Thanks for getting in touch!
This is a known issue, the fix is already released. Please update the SDK to the latest version.

Thanks,
Ivan

**Comment by kevoroid** [comment]
Great, thanks.
